import mongoose from "mongoose";
import "dotenv/config";
import Activity from "../models/Activities.js";

const BASE_URL = process.env.BASE_URL || "http://localhost:4000";

const data = [
  //--- Indoor Activities ---
  {
    name: "Clay Cafe",
    address: "199 Bree St, Cape Town City Centre, Cape Town, 8000",
    phone: "021 003 3130",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/claycafe/CCimg6.png`,
    ],
    rating: 4.5,
    prices: "R100 - R400",
    category: "IndoorActivities",
    about:
      "Clay Café is one of Cape Town's top pottery painting venues and family-friendly restaurants, offering a vibrant space for pottery painting and sip-and-paint events. As a ceramic painting venue and tapas bar, we provide everything you need to unleash your creativity while enjoying delicious food and drinks. Whether you're looking for a fun family day out, team-building activity, date night, or celebration, Clay Café is the perfect venue for a great family day out, team-building events, date nights and celebrations.",
    website: "https://claycafe.co.za/",
    openingHours: {
      monday: { open: "11:00 am", close: "17:00 pm" },
      tuesday: { open: "11:00 am", close: "18:00 pm" },
      wednesday: { open: "11:00 am", close: "22:00 pm" },
      thursday: { open: "11:00 am", close: "22:00 pm" },
      friday: { open: "11:00 am", close: "22:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm " },
      sunday: { open: "09:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "The Pottery",
    address: "41 The Dr, Camps Bay, Cape Town, 8005",
    phone: "087 470 0743",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/thepottery/TPimg6.png`,
    ],
    rating: 4.4,
    prices: "R100 - R200",
    category: "IndoorActivities",
    about: "Situated in the heart of the iconic Campsbay beachfront you can find our fourth Pottery store nationwide. The Pottery in Campsday is a must visit destination. We have designed the place to be an experience like no other. We are a family run business. Every customer will be made feel special and part of the family. Escape the hustle and bustle from the city and come make your soul feel enriched. From our vibey nightlife to enjoying a tasty cocktail and a delicious meal. Come have fun and laugh along the way.",
    website: "https://thepottery.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "21:00 pm" },
      friday: { open: "09:00 am", close: "21:00 pm" },
      saturday: { open: "09:00 am", close: "21:00 pm" },
      sunday: { open: "09:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Sip & Paint",
    address: "check on website for venues",
    phone: "066 038 6855",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/sipandpaint/SPimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/sipandpaint/SPimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/sipandpaint/SPimg3.png`,
    ],
    rating: 4.7,
    prices: "R200 - R400",
    category: "IndoorActivities",
    about: "Uncork your creativity for a good cause! We host monthly events at various venues across Cape Town, and the proceeds are used to fund our community development projects. We also offer private and corporate Paint & Sip events and can tailor the event to suit your needs. We also sell Paint & Sip kits, which are delivered to your door, Nationwide, allowing you to recreate one of our artworks from the comfort of your own home. Our formula is simple: The more you sip, the easier it gets. Paint & Sip events are designed for all artistic levels - from those who haven't picked up a paintbrush before, to advanced artists.",
    website: "https://www.call2care.org.za/paint-and-sip",
    openingHours: {
      monday: { open: "08:00 am", close: "17:00 pm" },
      tuesday: { open: "08:00 am", close: "17:00 pm" },
      wednesday: { open: "08:00 am", close: "17:00 pm" },
      thursday: { open: "08:00 am", close: "17:00 pm" },
      friday: { open: "08:00 am", close: "17:00 pm" },
      saturday: { open: "Closed", close: "Closed" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "2handsy Experience",
    address: "31 Newlands Ave, Newlands, Cape Town, 7700",
    phone: "061 864 2659",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/2handsyexperience/TEimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/2handsyexperience/TEimg2.png`, 
      `${BASE_URL}/uploads/activities/indooractivities/2handsyexperience/TEimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/2handsyexperience/TEimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/2handsyexperience/TEimg5.png`,
    ],
    rating: 5,
    prices: "R200 - R400",
    category: "IndoorActivities",
    about:
      "Looking for fun things to do in Cape Town this weekend? 2handsy is one of the city’s most unique and unforgettable experiences. Our interactive hand casting workshop is perfect for couples, families, friends, or team-building groups — and especially for travelers who want to take home a piece of Africa, literally. Whether you’re planning a date night in Cape Town, searching for weekend activities, or exploring creative experiences near you, 2handsy delivers more than just an activity. Expect music, games, laughter, and good vibes as you create a one-of-a-kind sculpture of your hands — a keepsake that lasts long after your trip. Great for birthdays, anniversaries, proposals, or anyone looking for unique things to do in Cape Town.",
    website: "https://www.2handsyexperience.com/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "12:00 pm", close: "18:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Artjamming",
    address: "Wembley Square, Solan Rd, Gardens, Cape Town, 8001",
    phone: "021 425 5050",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/artjamming/AJimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artjamming/AJimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artjamming/AJimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artjamming/AJimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artjamming/AJimg5.png`,
    ],
    rating: 4.2,
    prices: "R",
    category: "IndoorActivities",
    about: "Whether it’s playing, painting, sponging or spraying, it’s about putting on an apron to face a blank canvas and unleashing your own individual creativity that makes Artjamming™ the most fun you can have with a paintbrush. No drawing or painting skills are required, but for those who would like a helping hand or some inspiration, there are qualified artists at the studios to assist. Great for all ages and the perfect family activity. We also host birthday parties, team buildings and other events. For young artists, art students and art enthusiasts Artjamming™ is a great resource, not only for the various art materials available for sale. Let us Paintertain you!",
    website: "http://artisanpottery.com",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "Tuff Crowd",
    address: "CapeTown ZA, 243 Bree St, Gardens, Cape Town, 8001",
    phone: "064 971 6097",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/tuftcrowd/TCimg6.png`,
    ],
    rating: 4.8,
    prices: "R300 - R600",
    category: "IndoorActivities",
    about: "Welcome to our Tufting Studio! We are a dedicated artisanal workshop specializing in handcrafted tufted creations, designed to elevate your home decor. Whether you're in search of custom rugs, wall hangings, or other imaginative tufted pieces, we've got you covered. Our team of skilled artisans brings a wealth of experience to transform your vision into reality. Feel free to drop by anytime to explore a wide range of design and color options. We look forward to crafting unique tufted artworks that will add warmth and personality to your spaceA state-of-the-art indoor climbing facility for all skill levels.",
    website: "https://tuftcrowd.co.za/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Rapt—The Art of Indulgence",
    address: "39 Buitenkant St, Cape Town City Centre, Cape Town, 8000",
    phone: "021 201 7000",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/RaptArtOfIndulgence/RTimg6.png`,
    ],
    rating: 4.4,
    prices: "R200 - R600",
    category: "IndoorActivities",
    about:
      "Rapt—The Art of Indulgence is a creative studio and event space in the heart of Cape Town. We offer a variety of art classes and workshops, including painting, pottery, and mixed media. Our mission is to provide a welcoming and inspiring environment for people of all ages and skill levels to explore their creativity. Whether you're looking for a fun activity with friends or a unique date idea, Rapt is the perfect place to unleash your inner artist.",
    website: "https://www.instagram.com/raptindulgence/?hl=en",
    openingHours: {
      monday: { open: "10:00 am", close: "18:00 pm" },
      tuesday: { open: "10:00 am", close: "18:00 pm" },
      wednesday: { open: "10:00 am", close: "18:00 pm" },
      thursday: { open: "10:00 am", close: "18:00 pm" },
      friday: { open: "10:00 am", close: "18:00 pm" },
      saturday: { open: "10:00 am", close: "18:00 pm" },
      sunday: { open: "10:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "Barcaadia",
    address: "62 Hout St, Cape Town City Centre, Cape Town, 8000",
    phone: "",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/barcadia/Bimg6.png`,
    ],
    rating: 4.6,
    prices: "R100 - R500",
    category: "IndoorActivities",
    about: "Cape Town's first Retro Bar and Arcade Lounge. Unwind with classic arcade games, pinball machines, and a wide selection of craft beers and cocktails in a nostalgic atmosphere.",
    website: "https://www.barcadia.co.za/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "18:00 pm", close: "02:00 am" },
      wednesday: { open: "18:00 pm", close: "02:00 am" },
      thursday: { open: "18:00 pm", close: "02:00 am" },
      friday: { open: "18:00 pm", close: "02:00 am" },
      saturday: { open: "18:00 pm", close: "02:00 am" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "The Labia Theater",
    address: "68 Orange St, Gardens, Cape Town, 8000",
    phone: "021 424 5927",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/TheLabiaTheater/TLimg6.png`,
    ],
    rating: 4.6,
    prices: "R100 - R500",
    category: "IndoorActivities",
    about: "The Labia Theatre is one of the oldest independent movie theatres in Cape Town, South Africa. It is situated in Gardens, an inner-city suburb in the City Bowl.",
    website: "https://www.thelabia.co.za/",
    openingHours: {
      monday: { open: "11:00 am", close: "10:30 pm" },
      tuesday: { open: "11:00 am", close: "10:30 pm" },
      wednesday: { open: "11:00 am", close: "10:30 pm" },
      thursday: { open: "11:00 am", close: "10:30 pm" },
      friday: { open: "11:00 am", close: "10:30 pm" },
      saturday: { open: "11:00 am", close: "10:30 pm" },
      sunday: { open: "11:00 am", close: "10:30 pm" },
    },
  },
  {
    name: "Artelier By Anum",
    address: "11 Warwick Street, Claremont, Cape Town 7708",
    phone: "",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/artelierbyanum/AAimg6.png`,
    ],
    rating: 5,
    prices: "R400 - R700",
    category: "IndoorActivities",
    about:
      "Get creative with Us ! Our new Artelier by Anum workshops have arrived and now open for Ages +5 and Older. Explore, Create & Enjoy a variety of creative arts with us ! We have created Artelier by Anum , bringing you all the different types of creative arts new and trending activities for kids, couples , families or your besties get together ☕️ 👯‍♀️ Email us for bookings & inquiries artelierbyanum@gmail.com",
    website: "https://www.artelierbyanum.co.za",
    openingHours: {
      monday: { open: "", close: "" },
      tuesday: { open: "", close: "" },
      wednesday: { open: "", close: "" },
      thursday: { open: "", close: "" },
      friday: { open: "", close: "" },
      saturday: { open: "", close: "" },
      sunday: { open: "", close: "" },
    },
  },
  {
    name: "The Ice Station GrandWest Casino",
    address: "Grand West Casino, 1 Jakes Gerwel Drive, Acacia Park, Cape Town, 7460",
    phone: "021 535 2260",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/icestation/ISimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/icestation/ISimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/icestation/ISimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/icestation/ISimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/icestation/ISimg5.png`,
    ],
    rating: 4.5,
    prices: "R100 - R200",
    category: "IndoorActivities",
    about: "The first ice rink in Cape Town opened at the Goodwood Showgrounds in 1971. The rink changed hands in 1986 and the Cape Peninsula Ice Skating Club was formed, under the management of an elected committee. The property was sold in 1994 and the rink, renamed as The Ice Station was included in the GrandWest Casino & Entertainment World Development. An Olympic sized ice surface (60m x 30m), housed in a world class facility was constructed at GrandWest Casino and Entertainment World as a joint venture to build the arena with Sun International being the landlord and the CPISC the tenant, Cape Town in December 2000. Two skating disciplines and the public make use of the facilities at The Ice Station, including Ice Hockey & Figure Skating, with Figure Skating being the most popular.",
    website: "http://www.icerink.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "16:00 pm" },
      tuesday: { open: "10:00 am", close: "19:30 pm" },
      wednesday: { open: "10:00 am", close: "19:30 pm" },
      thursday: { open: "10:00 am", close: "19:30 pm" },
      friday: { open: "10:00 am", close: "23:30 pm" },
      saturday: { open: "10:00 am", close: "23:30 pm" },
      sunday: { open: "10:00 am", close: "20:30 pm" },
    },
  },
  {
    name: "Lets Go Bowling ",
    address: "Stadium on Main, Main Rd, Claremont, Cape Town, 7708",
    phone: "087 378 0891",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg1.png`,
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg2.png`,
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg3.png`,
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg4.png`,
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg5.png`,
      `${BASE_URL}/uploads/activities/indooractivities/LetsGoBowling/LGBimg6.png`,
    ],
    rating: 4.1,
    prices: "R100 - R300",
    category: "IndoorActivities",
    about: "Let's Entertainu Stadium, your one stop entertainment facility, boasting a 10 lane state of the art Tenpin Bowling centre, Laserblast, Crazy Golf, Kidz Play area, jungle gym and soft play, Pappa G’s Pizzeria, Amusement Centre, Pool and Strikers Lounge. Ideal venue for parties and team building. Check out our online booking system, unfortunately we do not take any telephone bookings, HAPPY TO SHARE WE OPERATE DURING LOAD SHEDDING",
    website: "https://www.letsentertainu.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "22:00 pm" },
      tuesday: { open: "10:00 am", close: "22:00 pm" },
      wednesday: { open: "10:00 am", close: "22:00 pm" },
      thursday: { open: "10:00 am", close: "22:00 pm" },
      friday: { open: "10:00 am", close: "22:00 pm" },
      saturday: { open: "10:00 am", close: "22:00 pm" },
      sunday: { open: "10:00 am", close: "21:00 pm" },
    },
  },

  //--- Outdoor Activities ---
  {
    name: "Waterfront Charters",
    address: "Shop 5 , Quay 5, V&A Waterfront, Victoria & Alfred Waterfront, Cape Town, 8002",
    phone: "021 418 3168",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/waterfrontcharters/WCimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/waterfrontcharters/WCimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/waterfrontcharters/WCimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/waterfrontcharters/WCimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/waterfrontcharters/WCimg5.png`,
    ],
    rating: 4.6,
    prices: "R200 - R600",
    category: "OutdoorActivities",
    about: "Established in 1991, Waterfront Charters is Cape Town's longest-running boat tour operator. Choose from luxurious catamarans to adventurous RIBs for daily scenic cruises or private charters, including popular sunset champagne cruises and Clifton excursions.",
    website: "http://www.waterfrontcharters.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Franschhoek Wine Tram",
    address: "Corner of Main Road, Cabriere St, Franschhoek, 7690",
    phone: "021 300 0338",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg5.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/franschhoekwinetram/FWTimg6.png`,
    ],
    rating: 4.6,
    prices: "R200 - R500",
    category: "OutdoorActivities",
    about: "The Franschhoek Wine Tram hop-on hop-off tour is one of the best ways to discover the true essence of the Franschhoek Valley. Passengers aboard the hop-on hop-off tour will experience a unique and leisurely way to see the Franschhoek Valley as they journey through rolling vineyards in a double-decker tram and open-air tram-bus stopping in at some of South Africa’s oldest and most distinguished wine estates. A combination of tram and tram-bus transports passengers around a loop of stops allowing them to hop-off at each stop and experience the activities on offer, be it wine tasting, a cellar tour, lunch or simply a stroll through the vineyards and when they are ready, hop-on to continue the tour.",
    website: "https://winetram.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Table mountain",
    address: "5821 Tafelberg Rd, Table Mountain (Nature Reserve), Cape Town, 8001",
    phone: "021 424 0015",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg5.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/tablemountain/TMimg6.png`,
    ],
    rating: 4.8,
    prices: "R100 - R400",
    category: "OutdoorActivities",
    about: "Table Mountain is a flat-topped mountain forming a prominent landmark overlooking the city of Cape Town in South Africa. It is a significant tourist attraction, with many visitors using the cableway or hiking to the top. The mountain has 8,200 plant species, of which around 80% are fynbos.",
    website: "http://botanicalgardenwalks.com",
    openingHours: {
      monday: { open: "08:00 am", close: "20:00 pm" },
      tuesday: { open: "08:00 am", close: "20:00 pm" },
      wednesday: { open: "08:00 am", close: "20:00 pm" },
      thursday: { open: "08:00 am", close: "20:00 pm" },
      friday: { open: "08:00 am", close: "20:00 pm" },
      saturday: { open: "08:00 am", close: "20:00 pm" },
      sunday: { open: "08:00 am", close: "20:00 pm" },
    },
  },
  {
    name: "Red Bus Tour",
    address: "Ticket Office outside the Aquarium, Dock Rd, Victoria & Alfred Waterfront, Cape Town, 8005",
    phone: "021 511 6000",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/redbustour/RBTimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/redbustour/RBTimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/redbustour/RBTimg3.png`,
    ],
    rating: 4.7,
    prices: "R100 - R300",
    category: "OutdoorActivities",
    about: "Explore Cape Town’s top attractions with City Sightseeing’s hop-on, hop-off bus tours. Visit Table Mountain, the V&A Waterfront, Camps Bay, and more at your own pace. Enjoy panoramic views, multilingual audio guides, and flexible ticket options. Book now for a fun, safe, and eco-friendly way to experience the Mother City!",
    website: "https://citysightseeing.co.za/en/cape-town",
    openingHours: {
      monday: { open: "08:00 am", close: "17:30 pm" },
      tuesday: { open: "08:00 am", close: "17:30 pm" },
      wednesday: { open: "08:00 am", close: "17:30 pm" },
      thursday: { open: "08:00 am", close: "17:30 pm" },
      friday: { open: "08:00 am", close: "17:30 pm" },
      saturday: { open: "08:00 am", close: "17:30 pm" },
      sunday: { open: "08:00 am", close: "17:30 pm" },
    },
  },
  {
    name: "Ocean Wonder",
    address: "",
    phone: "078 843 2356",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/oceanwonder/OWimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oceanwonder/OWimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oceanwonder/OWimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oceanwonder/OWimg4.png`,
    ],
    rating: 5,
    prices: "R100 - R400",
    category: "OutdoorActivities",
    about: "Ocean Wonder offers expert guided ccean wildlife experiences. I guarantee finding either dolphins or whales.",
    website: "http://www.oceanwonder.co.za/",
    openingHours: {
      monday: { open: "08:00 am", close: "19:00 pm" },
      tuesday: { open: "08:00 am", close: "19:00 pm" },
      wednesday: { open: "08:00 am", close: "19:00 pm" },
      thursday: { open: "08:00 am", close: "19:00 pm" },
      friday: { open: "08:00 am", close: "19:00 pm" },
      saturday: { open: "08:00 am", close: "19:00 pm" },
      sunday: { open: "08:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Chapman’s Drive",
    address: "Chapman's Peak Drive, Cape Town, 7976",
    phone: "",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/chapmanspeakdrive/CPDimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/chapmanspeakdrive/CPDimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/chapmanspeakdrive/CPDimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/chapmanspeakdrive/CPDimg4.png`,
    ],
    rating: 4.8,
    prices: "Free",
    category: "OutdoorActivities",
    about: "Chapman's Peak is a mountain on the western side of the Cape Peninsula, between Hout Bay and Noordhoek in Cape Town, South Africa. The road that runs along the mountain, Chapman's Peak Drive, is a major tourist attraction, offering stunning views of the Atlantic Ocean and the surrounding landscape.",
    website: "https://www.chapmanspeakdrive.co.za/",
    openingHours: {
      monday: { open: "", close: "" },
      tuesday: { open: "", close: "" },
      wednesday: { open: "", close: "" },
      thursday: { open: "", close: "" },
      friday: { open: "", close: "" },
      saturday: { open: "", close: "" },
      sunday: { open: "", close: "" },
    },
  },
  {
    name: "Lion's Head",
    address: " Signal Hill Rd, Signal Hill, Cape Town, 8001",
    phone: "086 110 6417",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg5.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/lionsheadhiking/LHHimg6.png`,
    ],
    rating: 4.8,
    prices: "Free",
    category: "OutdoorActivities",
    about: "Popular, screw-top hiking trail boasting panoramic views of the city alongside coastal views.",
    website: "https://hikelionshead.co.za/",
    openingHours: {
      monday: { open: "Open", close: "24 hours" },
      tuesday: { open: "Open", close: "24 hours" },
      wednesday: { open: "Open", close: "24 hours" },
      thursday: { open: "Open", close: "24 hours" },
      friday: { open: "Open", close: "24 hours" },
      saturday: { open: "Open", close: "24 hours" },
      sunday: { open: "Open", close: "24 hours" },
    },
  },
  {
    name: "Oranjezicht Farm Market",
    address: "Haul Road, Granger Bay Blvd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "083 628 3426",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/oranjezichtFarmMarket/OFMimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oranjezichtFarmMarket/OFMimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oranjezichtFarmMarket/OFMimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oranjezichtFarmMarket/OFMimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/oranjezichtFarmMarket/OFMimg5.png`,
    ],
    rating: 4.7,
    prices: "",
    category: "OutdoorActivities",
    about: "A good market is about more than buying groceries - it’s about striking up conversations, feeling part of a community, buying locally and eating with the seasons. Engage with the more than 65 producers of fresh produce, cheese, free-range meat, eggs and sustainably harvested fish. There is also plenty to eat on site for meat-lovers, vegans and vegetarians - its healthy and delicious. Located in a quiet part of the V&AW, there is seating, good music and sea views. Cash, credit card and Snapscan available. ATM on site. There is no fee to enter the market. Pedestrian entrances are open directly from The Granger Bay Parking Garage as well as on Beach Road, and cyclists, joggers and dog walkers are most welcome.",
    website: "https://ozcf.co.za/ozcfmarket/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "16:00 pm", close: "21:00 pm" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "08:30 am", close: "14:00 pm" },
      sunday: { open: "08:30 am", close: "14:00 pm" },
    },
  },
  {
    name: "The Old Biscuit Mill",
    address: "375 Albert Rd, Woodstock, Cape Town, 7915",
    phone: "021 447 8184",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg1.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg2.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg3.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg4.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg5.png`,
      `${BASE_URL}/uploads/activities/outdooractivities/theoldbiscuitmill/TOBMimg6.png`,
    ],
    rating: 4.4,
    prices: "R100 - R600",
    category: "OutdoorActivities",
    about: "A vibrant community in the heart of Woodstock where talented people come together to share, collaborate and show off their heartfelt passions. The Old Biscuit Mill is home to dynamic office spaces, a range of workshops and designer stores, decadent restaurants, food stalls as well as an inspiring line-up of day and night-markets, festivals and productions. Come and explore the Old Biscuit Mill and meet some of South Africa’s most innovative and creative designers, artists, photographers and connoisseurs of fine taste and décor. Moreover, the Mill – as it’s affectionately known – houses some of the city’s most charming architecture and, since its revitalisation over 10 years ago, has secured its spot as one of Cape Town’s favourite destinations.",
    website: "https://www.theoldbiscuitmill.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "16:00 pm" },
      tuesday: { open: "10:00 am", close: "16:00 pm" },
      wednesday: { open: "10:00 am", close: "16:00 pm" },
      thursday: { open: "10:00 am", close: "16:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { open: "09:00 am", close: "14:00 pm" },
    },
  },

  //--- Adventure ---
  {
    name: "Zerts Mocaa Museum",
    address: " S Arm Rd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "087 350 4777",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/zeitzmocaa/ZMimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/zeitzmocaa/ZMimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/zeitzmocaa/ZMimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/zeitzmocaa/ZMimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/zeitzmocaa/ZMimg5.png`,
    ],
    rating: 4.4,
    prices: "R100 - R300",
    category: "Adventure",
    about: "Zeitz Museum of Contemporary Art Africa is a public non-profit museum in Cape Town, South Africa. Zeitz MOCAA opened on September 22, 2017 as the largest museum of contemporary art from Africa and its diaspora. The museum is located in the Silo District at the Victoria & Alfred Waterfront in Cape Town.",
    website: "https://zeitzmocaa.museum/",
    openingHours: {
      monday: { open: "10:00 am", close: "18:00 pm" },
      tuesday: { open: "10:00 am", close: "18:00 pm" },
      wednesday: { open: "10:00 am", close: "18:00 pm" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "10:00 am", close: "18:00 pm" },
      saturday: { open: "10:00 am", close: "18:00 pm" },
      sunday: { open: "10:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "Greenpoint Park",
    address: "1 Fritz Sonnenberg Rd, Green Point, Cape Town, 8051",
    phone: "021 444 3903",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/greenpointpark/GPimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/greenpointpark/GPimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/greenpointpark/GPimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/greenpointpark/GPimg4.png`,
    ],
    rating: 4.7,
    prices: "R100 - R400",
    category: "Adventure",
    about: "Green Point Common, is a park in Green Point, Cape Town, in South Africa, where numerous playing fields and a golf course are situated. The Green Point Urban Park & Biodiversity Garden is just behind Mouille Point and has an entrance on Bay Road.",
    website: "http://whitewaterrraftingadventures.com",
    openingHours: {
      monday: { open: "07:00 am", close: "19:00 pm" },
      tuesday: { open: "07:00 am", close: "19:00 pm" },
      wednesday: { open: "07:00 am", close: "19:00 pm" },
      thursday: { open: "07:00 am", close: "19:00 pm" },
      friday: { open: "07:00 am", close: "19:00 pm" },
      saturday: { open: "07:00 am", close: "19:00 pm" },
      sunday: { open: "07:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Battery Park",
    address: "19 Dock Rd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "021 408 7600",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/batterypark/BPimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/batterypark/BPimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/batterypark/BPimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/batterypark/BPimg4.png`,
    ],
    rating: 4.6,
    prices: "Free",
    category: "Adventure",
    about: "Battery Park is a beautiful green space located in the V&A Waterfront in Cape Town, South Africa. It offers stunning views of Table Mountain and the harbor, making it a popular spot for picnics, leisurely walks, and outdoor activities. The park features well-maintained gardens, walking paths, and benches where visitors can relax and enjoy the scenery. It's an ideal place for families, couples, and solo travelers to unwind amidst nature while being close to the vibrant atmosphere of the waterfront.",
    website: "https://www.waterfront.co.za/battery-park-waterfront/",
    openingHours: {
      monday: { open: "07:00 am", close: "19:00 pm" },
      tuesday: { open: "07:00 am", close: "19:00 pm" },
      wednesday: { open: "07:00 am", close: "19:00 pm" },
      thursday: { open: "07:00 am", close: "19:00 pm" },
      friday: { open: "07:00 am", close: "19:00 pm" },
      saturday: { open: "07:00 am", close: "19:00 pm" },
      sunday: { open: "07:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Somewhere Nowhere",
    address: "84 Harrington St, District Six, Cape Town, 7925",
    phone: "077 277 1096",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg5.png`,
      `${BASE_URL}/uploads/activities/placestovisit/somewherenowhere/SNimg6.png`,
    ],
    rating: 4,
    prices: "R100 - R400",
    category: "Adventure",
    about: "Our rooftop setting isn’t just about the views – it’s your Pre’s destination. Gather around our pool for Sunset Cocktails and vibrant evenings. Digital nomads, travellers, and locals alike will find a home here – a place to connect, unwind, and be inspired. With curated interiors that celebrate Cape Town’s dynamic energy and a menu offering everything from rich espressos to unique local wines, Somewhere Nowhere is more than a café and bar – it’s where culture meets community.",
    website: "https://www.somewherenowherebar.co.za/",
    openingHours: {
      monday: { open: "07:00 am", close: "16:00 pm" },
      tuesday: { open: "07:00 am", close: "16:00 pm" },
      wednesday: { open: "07:00 am", close: "20:00 pm" },
      thursday: { open: "07:00 am", close: "20:00 pm" },
      friday: { open: "07:00 am", close: "20:00 pm" },
      saturday: { open: "07:00 am", close: "20:00 pm" },
      sunday: { open: "07:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "Kirstenbosch Botanical Garden",
    address: "Rhodes Dr, Newlands, Cape Town, 7735",
    phone: "021 799 8783",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/kirstenboschbotanicalgarden/KBGimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/kirstenboschbotanicalgarden/KBGimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/kirstenboschbotanicalgarden/KBGimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/kirstenboschbotanicalgarden/KBGimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/kirstenboschbotanicalgarden/KBGimg5.png`,
    ],
    rating: 4.8,
    prices: "R100 - R300",
    category: "Adventure",
    about: "Kirstenbosch is a botanical garden nestled at the eastern foot of Table Mountain in Cape Town. The garden is one of 10 National Botanical Gardens covering five of South Africa's six different biomes and administered by the South African National Biodiversity Institute.",
    website: "http://whitewaterrraftingadventures.com",
    openingHours: {
      monday: { open: "08:30 am", close: "17:30 pm" },
      tuesday: { open: "08:30 am", close: "17:30 pm" },
      wednesday: { open: "08:30 am", close: "17:30 pm" },
      thursday: { open: "08:00 am", close: "17:00 pm" },
      friday: { open: "08:30 am", close: "17:30 pm" },
      saturday: { open: "08:30 am", close: "17:30 pm" },
      sunday: { open: "08:30 am", close: "17:30 pm" },
    },
  },
  {
    name: "Cape Wheel",
    address: "The Lawns, Breakwater Blvd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: " 087 470 0696",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg5.png`,
      `${BASE_URL}/uploads/activities/placestovisit/capewheel/CWimg6.png`,
    ],
    rating: 4.5,
    prices: "R100 - R300",
    category: "Adventure",
    about: "Take in the breath-taking views of Granger Bay, Robben Island, Table Mountain, Signal Hill from our new location on Breakwater Boulevard at the V&A Waterfront. Our new location offers elevated views of Table Mountain, Signal Hill, the Cape Town stadium and so much more! Rediscover the magic of the V&A with our exciting new location – come ride the wheel and create unforgettable memories with friends and family.",
    website: "https://capewheel.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "22:00 pm" },
      tuesday: { open: "10:00 am", close: "22:00 pm" },
      wednesday: { open: "10:00 am", close: "22:00 pm" },
      thursday: { open: "10:00 am", close: "22:00 pm" },
      friday: { open: "10:00 am", close: "22:00 pm" },
      saturday: { open: "10:00 am", close: "22:00 pm" },
      sunday: { open: "10:00 am", close: "22:00 pm" },
    },
  },
  {
    name: "Signal Hill",
    address: "Signal Hill Rd, Signal Hill, Cape Town, 8001",
    phone: "",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/signalhill/SHimg1.png`,
    ],
    rating: 4.5,
    prices: "Free",
    category: "Adventure",
    about: "Signal Hill, or Lion's Rump, is a landmark flat-topped hill located in Cape Town, next to Lion's Head and Table Mountain. The hill was also known as The Lion's Flank, a term now obsolete. Together with Lion's Head, Signal Hill looks like a lion sphinx.",
    website: "http://mountainhikingexpeditions.com",
    openingHours: {
      monday: { open: "Open", close: "24 hours" },
      tuesday: { open: "Open", close: "24 hours" },
      wednesday: { open: "Open", close: "24 hours" },
      thursday: { open: "Open", close: "24 hours" },
      friday: { open: "Open", close: "24 hours" },
      saturday: { open: "Open", close: "24 hours" },
      sunday: { open: "Open", close: "24 hours" },
    },
  },
  {
    name: "Vredenheim Big Cats Park",
    address: "R310 Baden Powell Dr, Stellenbosch, Cape Town, 7600",
    phone: "021 881 3878",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg5.png`,
      `${BASE_URL}/uploads/activities/placestovisit/vredenheimbigcatspark/VBCPimg6.png`,
    ],
    rating: 4.4,
    prices: "R300 - R600",
    category: "Adventure",
    about: "Exciting whitewater rafting trips for thrill-seekers.",
    website: "http://whitewaterrraftingadventures.com",
    openingHours: {
      monday: { open: "09:00 am", close: "16:30 pm" },
      tuesday: { open: "09:00 am", close: "16:30 pm" },
      wednesday: { open: "09:00 am", close: "16:30 pm" },
      thursday: { open: "09:00 am", close: "16:30 pm" },
      friday: { open: "09:00 am", close: "16:30 pm" },
      saturday: { open: "09:00 am", close: "16:30 pm" },
      sunday: { open: "09:00 am", close: "16:30 pm" },
    },
  },
  {
    name: "The Planetarium",
    address: "25 Queen Victoria St, Cape Town City Centre, Cape Town, 8000",
    phone: "021 481 3800",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/theplanetarium/TPimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/theplanetarium/TPimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/theplanetarium/TPimg3.png`,
    ],
    rating: 4.4,
    prices: "R150 - R250",
    category: "Adventure",
    about: "The Iziko Planetarium and Digital Dome is the most advanced digital planetarium on the African continent. This world-class, multifunctional facility brings digital technology to Cape Town, creating a space of innovation and discovery where art, science and entertainment meet. The Iziko Planetarium and Digital Dome not only provides an immersive multi-sensory edutainment platform for artistic production – it is also used for cutting-edge scientific research to optimize South Africa’s eResearch and data visualization capacity. The Iziko Planetarium and Digital Dome makes virtual voyages of the universe possible, providing an unparalleled experience of animation and 360◦ cinema. Explore the inner workings of the human body, or the intricacies of an atomic structure Visit the most advanced digital planetarium on the African continent.",
    website: "https://www.iziko.org.za/museums/planetarium/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Aquarium",
    address: "Dock Rd, Victoria & Alfred Waterfront, Cape Town, 8002",
    phone: "021 418 3823",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg1.png`,
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg2.png`,
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg3.png`,
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg4.png`,
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg5.png`,
      `${BASE_URL}/uploads/activities/placestovisit/aquarium/Aimg6.png`,
    ],
    rating: 4.6,
    prices: "R100 - R300",
    category: "Adventure",
    about: "Where oceans meet... The southern tip of the African continent is the meeting place of two mighty and bountiful oceans, the Indian and the Atlantic. The Two Oceans Aquarium on the V&A Waterfront, Cape Town, is ideally positioned to showcase the incredible diversity of marine life found off the southern tip of Africa.",
    website: "http://mountainhikingexpeditions.com",
    openingHours: {
      monday: { open: "09:30 am", close: "18:00 pm" },
      tuesday: { open: "09:30 am", close: "18:00 pm" },
      wednesday: { open: "09:30 am", close: "18:00 pm" },
      thursday: { open: "09:30 am", close: "18:00 pm" },
      friday: { open: "09:30 am", close: "18:00 pm" },
      saturday: { open: "09:30 am", close: "18:00 pm" },
      sunday: { open: "09:30 am", close: "18:00 pm" },
    },
  },

  //--- Cultural Experiences ---
  {
    name: "Putt Putt",
    address: "Beach Rd, Sea Point, Cape Town, 8005",
    phone: "021 434 6805",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/puttputt/PPimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/puttputt/PPimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/puttputt/PPimg3.png`,
    ],
    rating: 4.3,
    prices: "R100 - R200",
    category: "Cultural",
    about:
      "Enjoy a fun-filled day of mini-golf with family and friends at Putt Putt Sea Point.",
    website: "https://www.instagram.com/puttputt/?hl=en",
    openingHours: {
      monday: { open: "09:00 am", close: "21:00 pm" },
      tuesday: { open: "09:00 am", close: "21:00 pm" },
      wednesday: { open: "09:00 am", close: "21:00 pm" },
      thursday: { open: "09:00 am", close: "21:00 pm" },
      friday: { open: "09:00 am", close: "21:00 pm" },
      saturday: { open: "09:00 am", close: "21:00 pm" },
      sunday: { open: "09:00 am", close: "21:00 pm" },
    },
  },
  {
    name: "Mojo Market",
    address: "30 Regent Rd, Sea Point, Cape Town, 8060",
    phone: "",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg3.png`,
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg4.png`,
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg5.png`,
      `${BASE_URL}/uploads/activities/dateideas/mojomarket/MMimg6.png`,
    ],
    rating: 4.5,
    prices: "R100 - R600",
    category: "Cultural",
    about: "Mojo Market is a vibrant indoor food and lifestyle market. Open 7-days-a-week with free entrance. Experience Food Stalls, Five Bars, Sports, Daily Live Music and Weekly & Monthly Events. Located right in the #HeartOfSeaPoint at 30 Regent Rd. There's #SomethingForEveryone at MOJO. Mojo is open every day, 365 days a year with the following trading hours: Coffee & Breakfast open daily from 8am Food Stalls & Bars: Sun - Thurs 11am-10pm Fri - Sat 11am-11pm Kindly email admin1@freedomproperties.co.za for all general enquiries.",
    website: "https://www.mojomarket.co.za/",
    openingHours: {
      monday: { open: "11:00 am", close: "23:00 pm" },
      tuesday: { open: "11:00 am", close: "23:00 pm" },
      wednesday: { open: "11:00 am", close: "23:00 pm" },
      thursday: { open: "11:00 am", close: "23:00 pm" },
      friday: { open: "11:00 am", close: "23:00 pm" },
      saturday: { open: "11:00 am", close: "23:00 pm" },
      sunday: { open: "11:00 am", close: "23:00 pm" },
    },
  },
  {
    name: "Cause Effect",
    address: "The Rocket Shed, 280 Dock Rd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "021 422 0266",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/causeeffect/CEimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/causeeffect/CEimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/causeeffect/CEimg3.png`,
      `${BASE_URL}/uploads/activities/dateideas/causeeffect/CEimg4.png`,
    ],
    rating: 4.2,
    prices: "R100 - R400",
    category: "Cultural",
    about:
      "Obtained number 53 in World's 50 Best Bars. Also nominated Top 10 Best International Cocktail Bar at the Spirited Awards - Obtained #55 in the World's Top 500 Bars - 2020. Won SA Cocktail Bar of the Year at the Bartending Accolades & Recognition (BAR) Awards.",
    website: "https://causeandeffect.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "01:00 am" },
      tuesday: { open: "10:00 am", close: "01:00 am" },
      wednesday: { open: "10:00 am", close: "01:00 am" },
      thursday: { open: "10:00 am", close: "01:00 am" },
      friday: { open: "10:00 am", close: "01:00 am" },
      saturday: { open: "09:00 am", close: "01:00 am" },
      sunday: { open: "09:00 am", close: "01:00 am" },
    },
  },
  {
    name: "Revved Up Cafe",
    address: "112 Buitengracht St, Cape Town City Centre, Cape Town, 8001",
    phone: "076 125 5962",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/revvedupcafe/RUCimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/revvedupcafe/RUCimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/revvedupcafe/RUCimg3.png`,
    ],
    rating: 4.1,
    prices: "R100 - R300",
    category: "Cultural",
    about:
      "Step into a world of delightful aromas and extraordinary flavors at Revved Up Café. Indulge in handcrafted coffees, connect with like-minded souls, and experience the magic of every sip. Join us for a coffee adventure like no other! Please note: ​During school holidays, public holidays, and weekends, we get very busy. To secure your spot and avoid disappointment, we highly recommend making a booking in advance.",
    website: "https://www.revvedupcafe.co.za/",
    openingHours: {
      monday: { open: "07:30 am", close: "17:00 pm" },
      tuesday: { open: "07:30 am", close: "17:00 pm" },
      wednesday: { open: "07:30 am", close: "17:00 pm" },
      thursday: { open: "07:30 am", close: "17:00 pm" },
      friday: { open: "07:30 am", close: "17:00 pm" },
      saturday: { open: "08:00 am", close: "13:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Outdoor movie Kirstenbosch",
    address: "0A Rhodes Ave, Wynberg NU (2), Cape Town, 7800",
    phone: "071 471 8728",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg3.png`,
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg4.png`,
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg5.png`,
      `${BASE_URL}/uploads/activities/dateideas/outdoormoviekirstenbosch/OMKimg6.png`,
    ],
    rating: 4.7,
    prices: "R300 - R500",
    category: "Cultural",
    about: "The Galileo Open Air Cinema invites you to enjoy a magical outdoor movie experience underneath a canopy of stars!",
    website: "https://thegalileo.co.za/open-air-cinema/kirstenbosch/",
    openingHours: {
      monday: { open: "08:00 am", close: "18:00 pm" },
      tuesday: { open: "08:00 am", close: "18:00 pm" },
      wednesday: { open: "08:00 am", close: "18:00 pm" },
      thursday: { open: "08:00 am", close: "18:00 pm" },
      friday: { open: "08:00 am", close: "18:00 pm" },
      saturday: { open: "08:00 am", close: "18:00 pm" },
      sunday: { open: "08:00 am", close: "18:00 pm" },
    },
  },
 {
    name: "Cookie co",
    address: "16 Bree St, Cape Town City Centre, Cape Town, 8000",
    phone: "066 185 5013",
    cuisine: "",
    category: "Cultural",
    images: [
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg1.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg2.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg3.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg4.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg5.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg6.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg7.png`,
      `${BASE_URL}/uploads/activities/dateideas/cookieco/Cimg8.png`,
    ],
    rating: 4.3,
    about:
      "Cookie Co. is the home of the original gourmet American-style cookie in South Africa. We pour our heart and soul into creating some of the most delectable, gooey, moreish cookies around that are designed solely to feed the insatiable appetite of true cookie fans across the country! Pair this with a cup of the finest coffee and you’ll get one of the sweetest combinations you can find! Speaking of sweet, we don’t stop with just cookies; oh no. In fact, we have such little self-control that we also decided to stock some of the world’s best ice-cream as well as a whole range of local and imported sweets and treats! We are cheat day central, the perfect blue Monday pick-me-up, the instiller of childhood nostalgia. We are Cookie Co!",
    website: "https://www.cookieco.co.za/",
    openingHours: {
      monday: { open: "07:00 am", close: "16:00 pm" },
      tuesday: { open: "07:00 am", close: "16:00 pm" },
      wednesday: { open: "07:00 am", close: "16:00 pm" },
      thursday: { open: "07:00 am", close: "16:00 pm" },
      friday: { open: "07:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { open: "09:00 am", close: "13:00 pm" },
    },
  },

  //--- Fun with Friends ---
   {
    name: "The Ice Station GrandWest Casino",
    address: "Grand West Casino, 1 Jakes Gerwel Drive, Acacia Park, Cape Town, 7460",
    phone: "021 535 2260",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/icestation/ISimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/icestation/ISimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/icestation/ISimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/icestation/ISimg4.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/icestation/ISimg5.png`,
    ],
    rating: 4.5,
    prices: "R100 - R200",
    category: "Friends",
    about: "The first ice rink in Cape Town opened at the Goodwood Showgrounds in 1971. The rink changed hands in 1986 and the Cape Peninsula Ice Skating Club was formed, under the management of an elected committee. The property was sold in 1994 and the rink, renamed as The Ice Station was included in the GrandWest Casino & Entertainment World Development. An Olympic sized ice surface (60m x 30m), housed in a world class facility was constructed at GrandWest Casino and Entertainment World as a joint venture to build the arena with Sun International being the landlord and the CPISC the tenant, Cape Town in December 2000. Two skating disciplines and the public make use of the facilities at The Ice Station, including Ice Hockey & Figure Skating, with Figure Skating being the most popular.",
    website: "http://www.icerink.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "16:00 pm" },
      tuesday: { open: "10:00 am", close: "19:30 pm" },
      wednesday: { open: "10:00 am", close: "19:30 pm" },
      thursday: { open: "10:00 am", close: "19:30 pm" },
      friday: { open: "10:00 am", close: "23:30 pm" },
      saturday: { open: "10:00 am", close: "23:30 pm" },
      sunday: { open: "10:00 am", close: "20:30 pm" },
    },
  },
  {
    name: "Lets Go Bowling ",
    address: "Stadium on Main, Main Rd, Claremont, Cape Town, 7708",
    phone: "087 378 0891",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg4.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg5.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/LetsGoBowling/LGBimg6.png`,
    ],
    rating: 4.1,
    prices: "R100 - R300",
    category: "Friends",
    about: "Let's Entertainu Stadium, your one stop entertainment facility, boasting a 10 lane state of the art Tenpin Bowling centre, Laserblast, Crazy Golf, Kidz Play area, jungle gym and soft play, Pappa G’s Pizzeria, Amusement Centre, Pool and Strikers Lounge. Ideal venue for parties and team building. Check out our online booking system, unfortunately we do not take any telephone bookings, HAPPY TO SHARE WE OPERATE DURING LOAD SHEDDING",
    website: "https://www.letsentertainu.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "22:00 pm" },
      tuesday: { open: "10:00 am", close: "22:00 pm" },
      wednesday: { open: "10:00 am", close: "22:00 pm" },
      thursday: { open: "10:00 am", close: "22:00 pm" },
      friday: { open: "10:00 am", close: "22:00 pm" },
      saturday: { open: "10:00 am", close: "22:00 pm" },
      sunday: { open: "10:00 am", close: "21:00 pm" },
    },
  },
  {
    name: "Rush Indoor",
    address: "25 Stegman Rd, Claremont, Cape Town, 7708",
    phone: "021 683 3841",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/rushindoor/RIimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/rushindoor/RIimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/rushindoor/RIimg3.png`,
    ],
    rating: 4.5,
    prices: "R160 - R400",
    category: "Friends",
    about: "Rush Claremont is a premier indoor adventure park in Cape Town, offering wall-to-wall fun for kids and families. From epic kids birthday parties to after-school energy burns, our park is packed with exciting attractions, including dodgeball courts, foam pits, and climbing walls.",
    website: "http://comedyclubhumorcity.com",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "11:00 am", close: "19:00 pm" },
      wednesday: { open: "11:00 am", close: "19:00 pm" },
      thursday: { open: "11:00 am", close: "19:00 pm" },
      friday: { open: "09:00 am", close: "20:00 pm" },
      saturday: { open: "09:00 am", close: "20:00 pm" },
      sunday: { open: "09:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "Total Ninja",
    address: "South Park Entrance, Black River Park, The Warehouse, Observatory, 7925",
    phone: "021 745 3089",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/totalninja/TNimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/totalninja/TNimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/totalninja/TNimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/totalninja/TNimg4.png`,
    ],
    rating: 4.6,
    prices: "R180 - R400",
    category: "Friends",
    about: "Our new Total Ninja Park is a supervised activity and fitness venue inspired by the need for individuals of all ages and abilities to achieve their own greatness. We are the largest inflatable and obstacle course in Africa. You can climb, balance, jump and swing across different obstacles using and developing your Ninja skills, plus we have the Warped Wall for every aspiring Ninja to conquer! A great place for family activities and for keeping fit, we welcome you on your Ninja journey.",
    website: "https://totalninja.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "21:00 pm" },
      tuesday: { open: "10:00 am", close: "21:00 pm" },
      wednesday: { open: "10:00 am", close: "21:00 pm" },
      thursday: { open: "10:00 am", close: "21:00 pm" },
      friday: { open: "10:00 am", close: "21:00 pm" },
      saturday: { open: "09:00 am", close: "21:00 pm" },
      sunday: { open: "09:00 am", close: "21:00 pm" },
    },
  },
  {
    name: "Century Karting",
    address: "0A Century Ave, Century City, Cape Town, 7441",
    phone: "064 978 0862",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg4.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg5.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/centurykarting/CKimg6.png`,
    ],
    rating: 4.5,
    prices: "R250 - R400",
    category: "Friends",
    about: "Indoor Go-Karting track with competitive racing events.",
    website: "https://www.karting.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "21:00 pm" },
      tuesday: { open: "09:00 am", close: "21:00 pm" },
      wednesday: { open: "09:00 am", close: "21:00 pm" },
      thursday: { open: "09:00 am", close: "21:00 pm" },
      friday: { open: "09:00 am", close: "21:00 pm" },
      saturday: { open: "09:00 am", close: "21:00 pm" },
      sunday: { open: "09:00 am", close: "21:00 pm" },
    },
  },
  {
    name: "RollerCade Battery",
    address: "R27, Corner or, Berkshire Blvd, Sunningdale, Cape Town, 7441",
    phone: "072 064 3963",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/rollercade/RBimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/rollercade/RBimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/rollercade/RBimg3.png`,
    ],
    rating: 4.5,
    prices: "R200 - R400",
    category: "Friends",
    about: "Rollercade is the 1st indoor roller-skating amusement park in Cape Town. Providing a safe and friendly environment for the entire family to enjoy roller-skating, a game of pool or just to sit back and enjoy the music. We have dedicated party areas and cater for company functions. Roller-skating keeps you on your feet and having fun. Space is limited & booking is essential. Please book in advance to avoid disappointment. “Just keep rolling",
    website: "https://rollercade.co.za/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "13:00 pm", close: "18:00 pm" },
      thursday: { open: "13:00 pm", close: "18:00 pm" },
      friday: { open: "13:00 pm", close: "19:00 pm" },
      saturday: { open: "10:00 am", close: "19:00 pm" },
      sunday: { open: "10:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "City Rock",
    address: "9 Milner St, Paarden Eiland, Cape Town, 7405",
    phone: "021 447 1326",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/cityrock/CRimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/cityrock/CRimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/cityrock/CRimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/cityrock/CRimg4.png`,
    ],
    rating: 4.8,
    prices: "R200 - R400",
    category: "Friends",
    about: "CityROCK is more than just a gym, it is where like-minded people meet and share their passion for climbing. Climbing is not like sitting on a cardio machine for what feels like hours – each climb is different and offers unique physical and mental challenges that will keep you coming back. Our facilities includes a huge roped climbing area, large bouldering section, automatic belays, a kids' section, a full fitness gym, a fully stocked outdoor gear shop, and a yoga & pilates studio.nd-up comedy shows featuring local and national comedians.",
    website: "http://comedyclubhumorcity.com",
    openingHours: {
      monday: { open: "11:00 am", close: "22:00 pm" },
      tuesday: { open: "11:00 am", close: "22:00 pm" },
      wednesday: { open: "11:00 am", close: "22:00 pm" },
      thursday: { open: "11:00 am", close: "22:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm" },
      sunday: { open: "09:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "Cool Running ",
    address: "Off Carl Cronje Dr, Tygervalley, Cape Town, 7530",
    phone: "021 949 4439",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/coolrunning/CRimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/coolrunning/CRimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/coolrunning/CRimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/coolrunning/CRimg4.png`,
    ],
    rating: 4.6,
    prices: "R100 - R300",
    category: "Friends",
    about: "",
    website: "https://www.coolrunnings.capetown/",
    openingHours: {
      monday: { open: "11:00 am", close: "18:00 pm" },
      tuesday: { open: "11:00 am", close: "18:00 pm" },
      wednesday: { open: "11:00 am", close: "18:00 pm" },
      thursday: { open: "11:00 am", close: "18:00 pm" },
      friday: { open: "11:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm" },
      sunday: { open: "09:00 am", close: "18:00 pm" },
    },
  },
  {
    name: "Sky Hi Ride",
    address: "28th Floor, Hotel Sky, 9 Lower Long St, Cape Town City Centre, Cape Town, 8001",
    phone: "021 879 5040",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/skyhiride/SHRimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/skyhiride/SHRimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/skyhiride/SHRimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/skyhiride/SHRimg4.png`,
    ],
    rating: 4.6,
    prices: "R200 - R400",
    category: "Friends",
    about: "Exhilarating, gravity-defying and a breath-taking drop, reaching a free fall speed of up to100km per hour and almost 4G’s. If this excites and thrills you then THIS is for you! The Sky Hi Ride on the 28th floor of Hotel Sky, towering 35 meters above the Cape Town City bowl giving you a bird’s eye view of one of the most beautiful cities in the World – Cape Town is one of only three in the world and the first of its kind in Africa. SKY-HI Ride will take you to new heights. After the exhilarating ride, don’t forget to visit the Sky-Hi Boutique to purchase your action-packed video along with your merchandise. The weather-permitting Sky-Hi Ride is limited to 10 riders per ride and is open daily between 09h00 and 21h00, to hotel guests & public",
    website: "https://sky-hiride.capetown/",
    openingHours: {
      monday: { open: "12:00 pm", close: "20:00 pm" },
      tuesday: { open: "12:00 pm", close: "20:00 pm" },
      wednesday: { open: "09:00 am", close: "20:00 pm" },
      thursday: { open: "09:00 am", close: "20:00 pm" },
      friday: { open: "09:00 am", close: "21:00 pm" },
      saturday: { open: "09:00 am", close: "21:00 pm" },
      sunday: { open: "09:00 am", close: "20:00 pm" },
    },
  },
  {
    name: "Atlantis Dunes",
    address: "0 Dassenberg Dr, Atlantis, Cape Town, 7349",
    phone: "021 054 0123",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/quadbiking/QBimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/quadbiking/QBimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/quadbiking/QBimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/quadbiking/QBimg4.png`,
    ],
    rating: 4.7,
    prices: "R300 - R1200",
    category: "Friends",
    about: "Atlantis Dunes offer adventurous experiences at the Atlantis Dunes just 45km from the city of Cape Town. Some of the adventures we offer are atv quad biking, Ultimate sandboarding and photoshoots. Pls use our website to check availability and make bookings , if you call in you will be referred to the website ;) We do not do bookings on WhatsApp or TripAdvisor or Viator or GetYourGuide , beware of scammers they often have multiple listings with different names , use gmail accounts and don't have proper websites",
    website: "https://www.atlantisdunes.com/",
    openingHours: {
      monday: { open: "08:30 am", close: "17:00 pm" },
      tuesday: { open: "08:30 am", close: "18:00 pm" },
      wednesday: { open: "08:30 am", close: "18:00 pm" },
      thursday: { open: "08:30 am", close: "18:00 pm" },
      friday: { open: "08:30 am", close: "18:00 pm" },
      saturday: { open: "08:30 am", close: "18:00 pm" },
      sunday: { open: "08:30 am", close: "18:00 pm" },
    },
  },
  {
    name: "Cape Kayak Adventure",
    address: "Three Anchor Bay, Cape Town, 8005",
    phone: "083 346 1146",
    cuisine: "",
    images: [
      `${BASE_URL}/uploads/activities/funwithfriends/capetownkayakadventure/CTKAimg1.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/capetownkayakadventure/CTKAimg2.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/capetownkayakadventure/CTKAimg3.png`,
      `${BASE_URL}/uploads/activities/funwithfriends/capetownkayakadventure/CTKAimg4.png`,
    ],
    rating: 4.9,
    prices: "R500 - R1000",
    category: "Friends",
    about: "Cape Kayak Adventures has been operating fun and safe kayak tours since 1995 on the Atlantic Seaboard. We are based in the heart of the Marine Protected Area of the Table Mountain National Park in Cape Town, South Africa. We offer guided kayak adventures in the morning, at sunset and under the glorious full moon, weather permitting. Come and explore the rich diversity of marine life, the kelp forests and a refreshing perspective of Cape Town and Table Mountain. Our experienced and knowledgeable guides will teach you the basics of kayaking and lead you on a safe and enjoyable tour of the Cape Town coastline. We love sharing our passion with our guests!.",
    website: "https://kayak.co.za/",
    openingHours: {
      monday: { open: "06:30 am", close: "17:00 pm" },
      tuesday: { open: "06:30 am", close: "17:00 pm" },
      wednesday: { open: "06:30 am", close: "17:00 pm" },
      thursday: { open: "06:30 am", close: "17:00 pm" },
      friday: { open: "06:30 am", close: "17:00 pm" },
      saturday: { open: "06:30 am", close: "17:00 pm" },
      sunday: { open: "06:30 am", close: "17:00 pm" },
    },
  },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Activity.deleteMany({});
    console.log("🗑️ Old activities deleted");

    await Activity.insertMany(data);
    console.log(`✅ Seeded ${data.length} entries`);
  } catch (err) {
    console.error("❌ Seed error:", err);
  } finally {
    await mongoose.disconnect();
  }
})();

