import mongoose from "mongoose";
import "dotenv/config";
import Activity from "../models/Activities.js";

const BASE_URL = process.env.BASE_URL || "http://localhost:4000";

const data = [
  //--- Indoor Activities ---
  {
    name: "Escape Room Challenge",
    address: "123 Mystery Lane, Cityville",
    phone: "555-1234",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1604014237744-5b0b1c7c1b5e"],
    rating: 4.8,
    category: "IndoorActivities",
    about:
      "A thrilling escape room experience where you solve puzzles to break out.",
    website: "http://escaperoomchallenge.com",
    openingHours: {
      monday: { open: "10:00", close: "22:00" },
      tuesday: { open: "10:00", close: "22:00" },
      wednesday: { open: "10:00", close: "22:00" },
      thursday: { open: "10:00", close: "22:00" },
      friday: { open: "10:00", close: "23:00" },
      saturday: { open: "09:00", close: "23:00" },
      sunday: { open: "09:00", close: "21:00" },
    },
  },
  {
    name: "Artisan Pottery Workshop",
    address: "456 Clay St, Artville",
    phone: "555-5678",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1601049541372-9b5b8e7d33c1"],
    rating: 4.6,
    category: "IndoorActivities",
    about: "Hands-on pottery classes for all skill levels in a cozy studio.",
    website: "http://artisanpottery.com",
    openingHours: {
      monday: { open: "11:00", close: "19:00" },
      tuesday: { open: "11:00", close: "19:00" },
      wednesday: { open: "11:00", close: "19:00" },
      thursday: { open: "11:00", close: "19:00" },
      friday: { open: "11:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "10:00", close: "18:00" },
    },
  },
  {
    name: "Indoor Rock Climbing Gym",
    address: "789 Climb Ave, Boulder City",
    phone: "555-9012",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93"],
    rating: 4.7,
    category: "IndoorActivities",
    about: "A state-of-the-art indoor climbing facility for all skill levels.",
    website: "http://indoorclimbinggym.com",
    openingHours: {
      monday: { open: "09:00", close: "21:00" },
      tuesday: { open: "09:00", close: "21:00" },
      wednesday: { open: "09:00", close: "21:00" },
      thursday: { open: "09:00", close: "21:00" },
      friday: { open: "09:00", close: "22:00" },
      saturday: { open: "08:00", close: "22:00" },
      sunday: { open: "08:00", close: "20:00" },
    },
  },

  //--- Outdoor Activities ---
  {
    name: "City Park Bike Rentals",
    address: "321 Cycle Rd, Greenfield",
    phone: "555-3456",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1525104885119-8806dd94ad58"],
    rating: 4.5,
    category: "OutdoorActivities",
    about: "Rent bikes and explore the scenic city park trails.",
    website: "http://cityparkbikerentals.com",
    openingHours: {
      monday: { open: "08:00", close: "20:00" },
      tuesday: { open: "08:00", close: "20:00" },
      wednesday: { open: "08:00", close: "20:00" },
      thursday: { open: "08:00", close: "20:00" },
      friday: { open: "08:00", close: "21:00" },
      saturday: { open: "07:00", close: "21:00" },
      sunday: { open: "07:00", close: "19:00" },
    },
  },
  {
    name: "Lakeside Kayak Tours",
    address: "654 Paddle St, Watertown",
    phone: "555-7890",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e"],
    rating: 4.9,
    category: "OutdoorActivities",
    about: "Guided kayak tours on the beautiful Lakeview Lake.",
    website: "http://lakesidekayaktours.com",
    openingHours: {
      monday: { open: "09:00", close: "18:00" },
      tuesday: { open: "09:00", close: "18:00" },
      wednesday: { open: "09:00", close: "18:00" },
      thursday: { open: "09:00", close: "18:00" },
      friday: { open: "09:00", close: "19:00" },
      saturday: { open: "08:00", close: "19:00" },
      sunday: { open: "08:00", close: "17:00" },
    },
  },
  {
    name: "Botanical Garden Walks",
    address: "987 Flora Blvd, Bloomtown",
    phone: "555-2345",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1501004318641-b39e6451bec6"],
    rating: 4.8,
    category: "OutdoorActivities",
    about: "Explore diverse plant species in our expansive botanical gardens.",
    website: "http://botanicalgardenwalks.com",
    openingHours: {
      monday: { open: "10:00", close: "17:00" },
      tuesday: { open: "10:00", close: "17:00" },
      wednesday: { open: "10:00", close: "17:00" },
      thursday: { open: "10:00", close: "17:00" },
      friday: { open: "10:00", close: "18:00" },
      saturday: { open: "09:00", close: "18:00" },
      sunday: { open: "09:00", close: "16:00" },
    },
  },

  //--- Adventure ---
  {
    name: "Mountain Hiking Expeditions",
    address: "135 Summit Rd, Hilltop",
    phone: "555-6789",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee"],
    rating: 4.9,
    category: "Adventure",
    about: "Guided hiking trips to explore challenging mountain trails.",
    website: "http://mountainhikingexpeditions.com",
    openingHours: {
      monday: { open: "06:00", close: "18:00" },
      tuesday: { open: "06:00", close: "18:00" },
      wednesday: { open: "06:00", close: "18:00" },
      thursday: { open: "06:00", close: "18:00" },
      friday: { open: "06:00", close: "19:00" },
      saturday: { open: "05:00", close: "19:00" },
      sunday: { open: "05:00", close: "17:00" },
    },
  },
  {
    name: "Whitewater Rafting Adventures",
    address: "246 Rapids Ln, Rivercity",
    phone: "555-0123",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1500375592092-40eb2168fd21"],
    rating: 4.7,
    category: "Adventure",
    about: "Exciting whitewater rafting trips for thrill-seekers.",
    website: "http://whitewaterrraftingadventures.com",
    openingHours: {
      monday: { open: "07:00", close: "17:00" },
      tuesday: { open: "07:00", close: "17:00" },
      wednesday: { open: "07:00", close: "17:00" },
      thursday: { open: "07:00", close: "17:00" },
      friday: { open: "07:00", close: "18:00" },
      saturday: { open: "06:00", close: "18:00" },
      sunday: { open: "06:00", close: "16:00" },
    },
  },
  {
    name: "Skydiving Experience",
    address: "369 Freefall St, Airville",
    phone: "555-4567",
    cuisine: "N/A",
    images: ["https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0"],
    rating: 4.8,
    category: "Adventure",
    about: "Tandem skydiving for an unforgettable adrenaline rush.",
    website: "http://skydivingexperience.com",
    openingHours: {
      monday: { open: "08:00", close: "16:00" },
      tuesday: { open: "08:00", close: "16:00" },
      wednesday: { open: "08:00", close: "16:00" },
      thursday: { open: "08:00", close: "16:00" },
      friday: { open: "08:00", close: "17:00" },
      saturday: { open: "07:00", close: "17:00" },
      sunday: { open: "07:00", close: "15:00" },
    },
  },

  //--- Relaxation ---
  {
    name: "Luxury Spa Retreat",
    address: "159 Serenity Blvd, Calm City",
    phone: "555-8910",
    cuisine: "N/A",
    images: ["https://example.com/images/spa1.jpg"],
    rating: 4.9,
    category: "Relaxation",
    about:
      "A full-service spa offering massages, facials, and wellness treatments.",
    website: "http://luxurysparetreat.com",
    openingHours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "09:00", close: "21:00" },
      sunday: { open: "09:00", close: "19:00" },
    },
  },
  {
    name: "Yoga and Meditation Center",
    address: "753 Zen St, Peaceville",
    phone: "555-2345",
    cuisine: "N/A",
    images: ["https://example.com/images/yoga1.jpg"],
    rating: 4.8,
    category: "Relaxation",
    about: "Daily yoga classes and meditation sessions for all levels.",
    website: "http://yogameditationcenter.com",
    openingHours: {
      monday: { open: "06:00", close: "21:00" },
      tuesday: { open: "06:00", close: "21:00" },
      wednesday: { open: "06:00", close: "21:00" },
      thursday: { open: "06:00", close: "21:00" },
      friday: { open: "06:00", close: "22:00" },
      saturday: { open: "07:00", close: "22:00" },
      sunday: { open: "07:00", close: "20:00" },
    },
  },
  {
    name: "Seaside Massage Therapy",
    address: "852 Ocean Dr, Beachtown",
    phone: "555-6789",
    cuisine: "N/A",
    images: ["https://example.com/images/massage1.jpg"],
    rating: 4.9,
    category: "Relaxation",
    about: "Professional massage services with a view of the ocean.",
    website: "http://seasidemassagetherapy.com",
    openingHours: {
      monday: { open: "10:00", close: "19:00" },
      tuesday: { open: "10:00", close: "19:00" },
      wednesday: { open: "10:00", close: "19:00" },
      thursday: { open: "10:00", close: "19:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "09:00", close: "20:00" },
      sunday: { open: "09:00", close: "18:00" },
    },
  },

  //--- Cultural Experiences ---
  {
    name: "Historical City Walking Tour",
    address: "147 Heritage St, Oldtown",
    phone: "555-0123",
    cuisine: "N/A",
    images: ["https://example.com/images/walking_tour1.jpg"],
    rating: 4.7,
    category: "Cultural",
    about:
      "Guided walking tours exploring the city's rich history and landmarks.",
    website: "http://historicalcitywalkingtour.com",
    openingHours: {
      monday: { open: "09:00", close: "17:00" },
      tuesday: { open: "09:00", close: "17:00" },
      wednesday: { open: "09:00", close: "17:00" },
      thursday: { open: "09:00", close: "17:00" },
      friday: { open: "09:00", close: "18:00" },
      saturday: { open: "08:00", close: "18:00" },
      sunday: { open: "08:00", close: "16:00" },
    },
  },
  {
    name: "Art Museum Guided Tours",
    address: "258 Gallery Rd, Artcity",
    phone: "555-4567",
    cuisine: "N/A",
    images: ["https://example.com/images/art_museum1.jpg"],
    rating: 4.8,
    category: "Cultural",
    about: "Explore world-class art collections with expert guides.",
    website: "http://artmuseumguidedtours.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "09:00", close: "20:00" },
      sunday: { open: "09:00", close: "17:00" },
    },
  },
  {
    name: "Cultural Dance Performances",
    address: "369 Rhythm St, Danceville",
    phone: "555-8901",
    cuisine: "N/A",
    images: ["https://example.com/images/dance1.jpg"],
    rating: 4.9,
    category: "Cultural",
    about:
      "Experience traditional and contemporary dance shows from around the world.",
    website: "http://culturaldanceperformances.com",
    openingHours: {
      monday: { open: "18:00", close: "22:00" },
      tuesday: { open: "18:00", close: "22:00" },
      wednesday: { open: "18:00", close: "22:00" },
      thursday: { open: "18:00", close: "22:00" },
      friday: { open: "18:00", close: "23:00" },
      saturday: { open: "17:00", close: "23:00" },
      sunday: { open: "17:00", close: "21:00" },
    },
  },

  //--- Fun with Friends ---
  {
    name: "Bowling Alley",
    address: "741 Strike Ln, Fun City",
    phone: "555-2345",
    cuisine: "N/A",
    images: ["https://example.com/images/bowling1.jpg"],
    rating: 4.6,
    category: "Friends",
    about: "A lively bowling alley with arcade games and a snack bar.",
    website: "http://bowlingalleyfuncity.com",
    openingHours: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    name: "Karaoke Bar",
    address: "852 Sing St, Musicville",
    phone: "555-6789",
    cuisine: "N/A",
    images: ["https://example.com/images/karaoke1.jpg"],
    rating: 4.7,
    category: "Friends",
    about: "Private karaoke rooms and a full bar for a fun night out.",
    website: "http://karaokebarmusicville.com",
    openingHours: {
      monday: { open: "17:00", close: "02:00" },
      tuesday: { open: "17:00", close: "02:00" },
      wednesday: { open: "17:00", close: "02:00" },
      thursday: { open: "17:00", close: "02:00" },
      friday: { open: "17:00", close: "03:00" },
      saturday: { open: "16:00", close: "03:00" },
      sunday: { open: "16:00", close: "01:00" },
    },
  },
  {
    name: "Comedy Club",
    address: "963 Laugh Ln, Humor City",
    phone: "555-0123",
    cuisine: "N/A",
    images: ["https://example.com/images/comedy1.jpg"],
    rating: 4.8,
    category: "Friends",
    about: "Stand-up comedy shows featuring local and national comedians.",
    website: "http://comedyclubhumorcity.com",
    openingHours: {
      monday: { open: "19:00", close: "23:00" },
      tuesday: { open: "19:00", close: "23:00" },
      wednesday: { open: "19:00", close: "23:00" },
      thursday: { open: "19:00", close: "23:00" },
      friday: { open: "19:00", close: "00:00" },
      saturday: { open: "18:00", close: "00:00" },
      sunday: { open: "18:00", close: "22:00" },
    },
  },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Activity.deleteMany({});
    console.log("🗑️ Old activities deleted");

    await Activity.insertMany(data);
    console.log(`✅ Seeded ${data.length} entries`);
  } catch (err) {
    console.error("❌ Seed error:", err);
  } finally {
    await mongoose.disconnect();
  }
})();

