import mongoose from "mongoose";
import "dotenv/config";
import Store from "../models/Store.js";

const BASE_URL = process.env.BASE_URL || "http://localhost:4000";

const data = [
  // --- Vintage ---
  {
    name: "Bahamas Thrift",
    address: "46 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "079 086 1248",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about: "We sell vintage clothes and street wear",
    website: "http://www.bahamasthrift.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "18:00 pm" },
      tuesday: { open: "10:00 am", close: "18:00 pm" },
      wednesday: { open: "10:00 am", close: "18:00 pm" },
      thursday: { open: "10:00 am", close: "18:00 pm" },
      friday: { open: "10:00 am", close: "18:00 pm" },
      saturday: { open: "10:00 am", close: "18:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "KaapDiem Thrift",
    address: "92 Wale St, Cape Town City Centre, Cape Town, 8001",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg6.png`,
    ],
    rating: 4.6,
    category: "Vintage",
    about: "We love pre-loved clothing",
    website: "https://www.instagram.com/kaapdiemthrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Barley Bloset",
    address: "114 Lower Main Rd, Observatory, Cape Town",
    phone: "063 178 9456",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg5.png`,
    ],
    rating: 4.6,
    category: "Vintage",
    about:
      "Consciously Curated Second Hand Shopping Barley's Bloset is a thrift and vintage clothing store in Observatory, Cape Town, which is curated by Carley Adonis. It operates both a physical store and an online shop, and also hosts regular markets.",
    website: "https://barleysbloset.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "17:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "YBMV Collective",
    address: " 285B Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "077 444 2331",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "YBMV Collective, originally named You Butterfly Me Vintage, started in 2016 as a part-time high-school passion project of our founder. In 2020, our team grew & our brand developed into a full-time position, which we re-branded & re-established as a collective space selling a wide selection of fashion products. We offer high-quality, carefully curated fashion items for our fashion-forward & conscious consumers. Now, in 2025 you can shop YBMV Collective all week at our shop in Observatory as well as every weekend at The Neighbourgoods Market at The Old Biscuit Mill, in Woodstock!",
    website: "https://ybmvcollective.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { open: "11:00 am", close: "15:00 pm" },
    },
  },
  {
    name: "Coat King",
    address: "145 M4, Claremont, Cape Town, 7708",
    phone: "021 683 0504",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg6.png`,
    ],
    rating: 4.4,
    category: "Vintage",
    about:
      "A treasure trove of vintage clothing and accessories from the 60s, 70s, and 80s.",
    website: "https://www.instagram.com/coat_king_wholesalers/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Just Your Luck Vintage Store",
    address: "69 Lower Main Rd, Observatory, Cape Town, 7780",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "🍀Welcome to Justyourluck 🍀 Discover a unique shopping experience where quality meets affordability. We offer a curated selection of both second-hand and new clothing, ensuring that everyone can find stylish pieces without breaking the bank. Whether you’re hunting for vintage finds or the latest trends, we've got something for everyone. Come explore our collection at 69 Lower Main Road Observatory.",
    website: "https://www.instagram.com/justyourluck_cpt/?hl=en",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Qeftys",
    address: "66 Albert Road, Cape Town",
    phone: "067 684 8561",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg5.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "Qeftys is a store that holds high quality clothing for men and women, Local and foreign brands included. Our focus is on making luxury quality affordable. Giving you exclusive items. Our clothing are at times, 1of 1, and at times 2 pieces per item, giving a taste of exclusivity to your fashion taste.",
    website: "https://www.instagram.com/qeftys/",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "15:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Tears Charity",
    address: "281 Main Rd, Retreat, Cape Town, 7950",
    phone: "074 168 8514",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg5.png`,
    ],
    rating: 4.3,
    category: "Vintage",
    about:
      "TEARS Charity Shops bring in about a third of our income. Without the money that our shops bring in, we would not be able to help nearly as many dogs and cats as we do. Always accepting donations.",
    website: "https://tears.org.za/thrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "13:00 pm" },
    },
  },
  // --- Modern ---
  {
    name: "Chic Boutique",
    address: "789 Fashion Rd, Metropolis",
    phone: "555-8765",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage3.jpg`],
    rating: 4.8,
    category: "Modern",
    about:
      "Contemporary fashion boutique featuring the latest trends and designer labels.",
    website: "http://www.chicboutique.com",
    openingHours: {
      monday: { open: "10:00", close: "19:00" },
      tuesday: { open: "10:00", close: "19:00" },
      wednesday: { open: "10:00", close: "19:00" },
      thursday: { open: "10:00", close: "19:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "10:00", close: "21:00" },
      sunday: { open: "12:00", close: "17:00" },
    },
  },
  {
    name: "Urban Style",
    address: "321 Trendy Ln, Uptown",
    phone: "555-4321",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage4.jpg`],
    rating: 4.6,
    category: "Modern",
    about:
      "A stylish boutique offering a mix of casual and formal wear for the modern individual.",
    website: "http://www.urbanstyle.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  // --- Handmade ---
  {
    name: "Crafted Creations",
    address: "654 Artisan St, Craftsville",
    phone: "555-6789",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage5.jpg`],
    rating: 4.9,
    category: "Handmade",
    about:
      "A charming shop showcasing handmade goods from local artisans, including jewelry, pottery, and textiles.",
    website: "http://www.craftedcreations.com",
    openingHours: {
      monday: { open: "11:00", close: "17:00" },
      tuesday: { open: "11:00", close: "17:00" },
      wednesday: { open: "11:00", close: "17:00" },
      thursday: { open: "11:00", close: "17:00" },
      friday: { open: "11:00", close: "19:00" },
      saturday: { open: "11:00", close: "19:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  {
    name: "Artisan Alley",
    address: "987 Handmade Blvd, Creativetown",
    phone: "555-9876",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage1.jpg`],
    rating: 4.8,
    category: "Handmade",
    about:
      "Featuring a variety of handcrafted items, from candles and soaps to artwork and home decor.",
    website: "http://www.artisanalley.com",
    openingHours: {
      monday: { open: "11:00", close: "17:00" },
      tuesday: { open: "11:00", close: "17:00" },
      wednesday: { open: "11:00", close: "17:00" },
      thursday: { open: "11:00", close: "17:00" },
      friday: { open: "11:00", close: "19:00" },
      saturday: { open: "11:00", close: "19:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  // --- Bookstores ---
  {
    name: "Obz Books",
    address: "76 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "082 892 8172",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg6.png`,
    ],
    rating: 4.3,
    category: "Bookstores",
    about:
      "A cozy independent bookstore with a curated selection of books, stationery, and gifts.",
    website: "https://www.obzbooks.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm" },
      sunday: { open: "10:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "Tears Charity",
    address: "281 Main Rd, Retreat, Cape Town, 7950",
    phone: "074 168 8514",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg6.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg7.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg8.png`,
    ],
    rating: 4.3,
    category: "Bookstores",
    about:
      "TEARS Charity Shops bring in about a third of our income. Without the money that our shops bring in, we would not be able to help nearly as many dogs and cats as we do. Always accepting donations.",
    website: "https://tears.org.za/thrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "13:00 pm" },
    },
  },
  {
    name: "The Book Lounge",
    address:
      "Cnr Buitenkant, 71 Roeland St, Cape Town City Centre, Cape Town, 8001",
    phone: "021 462 2425",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg6.png`,
    ],
    rating: 4.7,
    category: "Bookstores",
    about:
      "An independent bookshop in the heart of Cape Town - we are passionate about what we do!",
    website: "https://booklounge.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { open: "10:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "The Bookworm",
    address: "20 1st Ave, Fish Hoek, Cape Town, 7974",
    phone: "079 309 8435",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "A delightful shop offering a wide range of books, journals, and high-quality stationery products.",
    website: "http://www.paperandink.com",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Paper Moon Book Shop",
    address: "105 Roodebloem Rd, Woodstock, Cape Town, 7925",
    phone: "082 444 0444",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg6.png`,
    ],
    rating: 4.8,
    category: "Bookstores",
    about:
      "Carefully selected second hand books, in almost new condition We also sell: - Art prints - Magazines We also have another store in York Road, Muizenberg.",
    website: "https://www.instagram.com/papermoon.muizenberg/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "17:00 pm" },
      sunday: { open: "10:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Readers Den",
    address: "25 Barnstaple Rd, Wynberg, Cape Town, 7800",
    phone: "021 671 9551",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "Family-owned shop since 1992 supplying imported comic books, graphic novels, action figures & manga.",
    website: "https://readersden.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Bikini Beach Books",
    address: "41 Beach Rd, Gordons Bay Central, Cape Town, 7151",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg6.png`,
    ],
    rating: 4.4,
    category: "Bookstores",
    about:
      "This laid-back outpost for reading material has piles of secondhand titles on diverse subjects.",
    website: "https://www.instagram.com/bikini-beach-books/?hl=en",
    openingHours: {
      monday: { open: "20:00 am", close: "19:00 pm" },
      tuesday: { open: "20:00 am", close: "19:00 pm" },
      wednesday: { open: "20:00 am", close: "19:00 pm" },
      thursday: { open: "20:00 am", close: "19:00 pm" },
      friday: { open: "20:00 am", close: "19:00 pm" },
      saturday: { open: "20:00 am", close: "19:00 pm" },
      sunday: { open: "20:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Bargain Books",
    address: "Shop G44&45, Forest Dr Service Rd, Pinelands, Cape Town, 7405",
    phone: "021 532 2217",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg6.png`,
    ],
    rating: 4.7,
    category: "Bookstores",
    about:
      "Bargain Books is South Africa’s most budget-friendly and widest ranged book retailer. Spanning over more than 80 stores across all nine provinces, our primary intention is to provide good books at the best possible prices, in a welcoming environment. We choose our dedicated and passionate booksellers very carefully and try our best to be attentive to every segment of the reading community. We are passionate about bestsellers, new authors; and children's books - recognising the importance of affordable reading in childhood. We want you to have a positive experience in our stores, get value for your money, a wide range to choose from, and enjoy a rewarding and stress-free visit.",
    website: "https://www.instagram.com/bargainbookssa/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Clarkes Book Shop",
    address: "199 Long St, Cape Town City Centre, Cape Town, 8001",
    phone: "021 423 5739",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "Independent bookshop specialising in African and South African books",
    website: "https://clarkesbooks.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "10:30 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  // --- Markets ---
  {
    name: "Dorp Street Sunday Market",
    address: "53 dorp street, Stellenbosch, Western Cape 7600",
    phone: "074 704 7800",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg6.png`,
    ],
    rating: 4.3,
    category: "Markets",
    about:
      "A fresh, open-air streetside market in Stellenbosch, Dorp Street. The market is filled with hard working entrepreneurs and small businesses. Come and see what the buzz is about and enjoy a relaxing day of strolling through the beautiful Winelands nature scenery.",
    website: "https://www.instagram.com/dorpstreetsundaymarket/?hl=en",
  },
  {
    name: "The Candor Market",
    address: "Sandown Road, Campground Rd, Rondebosch, Cape Town, 7700",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg6.png`,
    ],
    rating: 5,
    category: "Markets",
    about:
      "Candor Market is a curated community space empowering the circular economy through conscious entrepreneurship. We bring together small businesses and mindful consumers in a welcoming atmosphere dedicated to positive impact, sustainability, and wholesome vibes!",
    website: "https://www.thecandormarket.com/",
    openingHours: {
      saturday: { open: "Select Saturdays only" },
    },
  },
  {
    name: "Godwood Bargains Market",
    address: "54 Milton Rd, Goodwood Estate, Cape Town, 7460",
    phone: "064 529 8020",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg3.png`,
    ],
    rating: 4.5,
    category: "Markets",
    about:
      "Turn your closet into cash or enjoy shopping incredible bargains on all things preloved fashion,vintage, fluffy, glitzy, vintage, home decor and so much more ... An amazing vibe with fabulous and friendly vendors. More than just a market...we are a family with a passion for keeping things circular. Find us every first Saturday if the month...don't miss it as each month brings new treasures!",
    website: "https://www.instagram.com/thegoodwoodmarket/?hl=en",
    openingHours: {
      monday: { close: "Closed" },
      tuesday: { close: "Closed" },
      wednesday: { close: "Closed" },
      thursday: { close: "Closed" },
      friday: { close: "Closed" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Milnerton Market",
    address: "126 Marine Dr, Paarden Eiland, Cape Town, 7405",
    phone: "021 551 7879",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg5.png`,
    ],
    rating: 4.1,
    category: "Markets",
    about:
      "Milnerton Market is a vibrant hub for thrift lovers and vintage enthusiasts. Discover unique second-hand treasures, retro fashion, and nostalgic finds in a lively atmosphere. Whether you're hunting for classic clothing or quirky collectibles, Milnerton Market offers a diverse range of pre-loved items that cater to all tastes. Join us for a fun and sustainable shopping experience!",
    website: "https://www.instagram.com/milnertonmarket/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "08:00 am", close: "14:00 pm" },
      sunday: { open: "08:00 am", close: "15:00 pm" },
    },
  },
  {
    name: "Flea Market",
    address: "Western Cape, South Africa, Muizenberg",
    phone: "021 788 7881",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/FleaMarket/FMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/FleaMarket/FMimg2.png`,
    ],
    rating: 4.2,
    category: "Markets",
    about:
      "The Muizenberg Flea Market is a vibrant hub for thrift lovers and vintage enthusiasts. Discover unique second-hand treasures, retro fashion, and nostalgic finds in a lively atmosphere. Whether you're hunting for classic clothing or quirky collectibles, the Muizenberg Flea Market offers a diverse range of pre-loved items that cater to all tastes. Join us for a fun and sustainable shopping experience!",
    website: "https://www.instagram.com/muizenberg-flea-market/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "Closed", close: "Closed" },
      sunday: { open: "08:30 am", close: "17:00 pm" },
    },
  },
  {
    name: "Oranjezicht Farm Market",
    address:
      "Haul Road, Granger Bay Blvd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "083 628 3426",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg5.png`,
    ],
    rating: 4.7,
    category: "Markets",
    about:
      "A good market is about more than buying groceries - it’s about striking up conversations, feeling part of a community, buying locally and eating with the seasons. Engage with the more than 65 producers of fresh produce, cheese, free-range meat, eggs and sustainably harvested fish. There is also plenty to eat on site for meat-lovers, vegans and vegetarians - its healthy and delicious. Located in a quiet part of the V&AW, there is seating, good music and sea views. Cash, credit card and Snapscan available. ATM on site. There is no fee to enter the market. Pedestrian entrances are open directly from The Granger Bay Parking Garage as well as on Beach Road, and cyclists, joggers and dog walkers are most welcome.",
    website: "https://www.instagram.com/ozcfarm/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "04:00 am", close: "21:00 pm" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "08:00 am", close: "14:00 pm" },
      sunday: { open: "08:30 am", close: "14:00 pm" },
    },
  },
  {
    name: "Trench Town Pop Ups",
    address: "143 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "083 298 8388",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg1.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg2.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg3.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg4.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg5.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg6.png`,
    ],
    rating: 4.6,
    category: "Markets",
    about:
      "We are Trench Town Pop Ups. A collaborative 3 day a week permanent pop up stall on the lovely grounds of Trench Town Obs. Thursday evenings are a vibey night market whilst Saturday mornings is the big family market. Come check out the best vendors, food, vibe and restaurant.",
    website: "https://www.instagram.com/trenchtown_obs/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "04:00 am", close: "20:00 pm" },
      friday: { open: "12:00 am", close: "20:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Neighbourgoods Market",
    address: "373 Albert Rd, Woodstock, Cape Town, 7925",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg6.png`,
    ],
    rating: 4.5,
    category: "Markets",
    about:
      "The Neighbourgoods Market is a weekly market place and cultural event held at The Old Biscuit Mill in Woodstock, Cape Town. Held every weekend of the year, this is the essential meeting ground for the city's cosmopolitan community to gather and enjoy the bounty of food, design, fashion and music that define the Mother City. Now in it’s 18th year, this award-winning market features over 100 specialty traders every Saturday, creating a weekly showcase for Cape Town’s most exciting street food chefs, artisanal producers, local designers, musicians and merchants to gather and display their work in a festive celebration of local creative culture.",
    website: "https://www.instagram.com/neighbourgoodsmarket/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "09:00 am", close: "15:00 pm" },
      sunday: { open: "10:00 am", close: "15:00 pm" },
    },
  },
  // --- Music ---
  {
    name: "Vinyl Vibes",
    address: "357 Music Ave, Soundtown",
    phone: "555-2589",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage1.jpg`],
    rating: 4.9,
    category: "Music",
    about:
      "A haven for vinyl enthusiasts, offering a wide selection of records across various genres.",
    website: "http://www.vinylvibes.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  {
    name: "Sound Sanctuary",
    address: "753 Groove St, Beatcity",
    phone: "555-3697",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage2.jpg`],
    rating: 4.8,
    category: "Music",
    about:
      "A unique music store offering vinyl records, CDs, and music memorabilia.",
    website: "http://www.soundsanctuary.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  // --- Comic ---
  {
    name: "Comic Corner",
    address: "159 Hero Ln, Fandom City",
    phone: "555-7412",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage3.jpg`],
    rating: 4.7,
    category: "Comic",
    about:
      "A paradise for comic book lovers, featuring a vast collection of comics, graphic novels, and collectibles.",
    website: "http://www.comiccorner.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
  {
    name: "Collectible Haven",
    address: "357 Treasure St, Geekville",
    phone: "555-8523",
    cuisine: "N/A",
    images: [`${BASE_URL}/uploads/stores/vintage4.jpg`],
    rating: 4.6,
    category: "Comic",
    about:
      "Offering a wide range of collectibles, from action figures and toys to rare comics and memorabilia.",
    website: "http://www.collectiblehaven.com",
    openingHours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "18:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: { open: "12:00", close: "16:00" },
    },
  },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Store.deleteMany({});
    console.log("🗑️ Old stors deleted");

    await Store.insertMany(data);
    console.log(`✅ Seeded ${data.length} entries`);
  } catch (err) {
    console.error("❌ Seed error:", err);
  } finally {
    await mongoose.disconnect();
  }
})();
