import mongoose from "mongoose";
import "dotenv/config";
import Store from "../models/Store.js";

const BASE_URL = process.env.BASE_URL || "http://localhost:4000";

const data = [
    // --- Vintage ---
    {
        name: "Retro Revival",
        address: "123 Vintage St, Cityville",
        phone: "555-1234",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage1.jpg`],
        rating: 4.5,
        category: "Vintage",
        about: "A treasure trove of vintage clothing and accessories from the 60s, 70s, and 80s.",
        website: "http://www.retrorevival.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    {
        name: "Timeless Treasures",
        address: "456 Classic Ave, Townsville",
        phone: "555-5678",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage2.jpg`],
        rating: 4.7,
        category: "Vintage",
        about: "Curated collection of vintage furniture, home decor, and unique finds.",
        website: "http://www.timelesstreasures.com",
        openingHours: {
            monday: { open: "11:00", close: "17:00" },
            tuesday: { open: "11:00", close: "17:00" },
            wednesday: { open: "11:00", close: "17:00" },
            thursday: { open: "11:00", close: "17:00" },
            friday: { open: "11:00", close: "19:00" },
            saturday: { open: "11:00", close: "19:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    // --- Modern ---
    {
        name: "Chic Boutique",
        address: "789 Fashion Rd, Metropolis",
        phone: "555-8765",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage3.jpg`],
        rating: 4.8,
        category: "Modern",
        about: "Contemporary fashion boutique featuring the latest trends and designer labels.",
        website: "http://www.chicboutique.com",
        openingHours: {
            monday: { open: "10:00", close: "19:00" },
            tuesday: { open: "10:00", close: "19:00" },
            wednesday: { open: "10:00", close: "19:00" },
            thursday: { open: "10:00", close: "19:00" },
            friday: { open: "10:00", close: "21:00" },
            saturday: { open: "10:00", close: "21:00" },
            sunday: { open: "12:00", close: "17:00" },
        },
    },
    {
        name: "Urban Style",
        address: "321 Trendy Ln, Uptown",
        phone: "555-4321",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage4.jpg`],
        rating: 4.6,
        category: "Modern",
        about: "A stylish boutique offering a mix of casual and formal wear for the modern individual.",
        website: "http://www.urbanstyle.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    // --- Handmade ---
    {
        name: "Crafted Creations",
        address: "654 Artisan St, Craftsville",
        phone: "555-6789",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage5.jpg`],
        rating: 4.9,
        category: "Handmade",
        about: "A charming shop showcasing handmade goods from local artisans, including jewelry, pottery, and textiles.",
        website: "http://www.craftedcreations.com",
        openingHours: {
            monday: { open: "11:00", close: "17:00" },
            tuesday: { open: "11:00", close: "17:00" },
            wednesday: { open: "11:00", close: "17:00" },
            thursday: { open: "11:00", close: "17:00" },
            friday: { open: "11:00", close: "19:00" },
            saturday: { open: "11:00", close: "19:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    {
        name: "Artisan Alley",
        address: "987 Handmade Blvd, Creativetown",
        phone: "555-9876",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage1.jpg`],
        rating: 4.8,
        category: "Handmade",
        about: "Featuring a variety of handcrafted items, from candles and soaps to artwork and home decor.",
        website: "http://www.artisanalley.com",
        openingHours: {
            monday: { open: "11:00", close: "17:00" },
            tuesday: { open: "11:00", close: "17:00" },
            wednesday: { open: "11:00", close: "17:00" },
            thursday: { open: "11:00", close: "17:00" },
            friday: { open: "11:00", close: "19:00" },
            saturday: { open: "11:00", close: "19:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    // --- Bookstores ---
    {
        name: "The Reading Nook",
        address: "159 Bookworm Rd, Literaville",
        phone: "555-2468",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage2.jpg`],
        rating: 4.9,
        category: "Bookstores",
        about: "A cozy independent bookstore with a curated selection of books, stationery, and gifts.",
        website: "http://www.readingnook.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    {
        name: "Paper & Ink",
        address: "753 Stationery Ln, Writecity",
        phone: "555-1357",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage3.jpg`],
        rating: 4.7,
        category: "Bookstores",
        about: "A delightful shop offering a wide range of books, journals, and high-quality stationery products.",
        website: "http://www.paperandink.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    // --- Markets ---
    {
        name: "Thrift Market",
        address: "852 Bargain St, Savetown",
        phone: "555-3698",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage4.jpg`],
        rating: 4.6,
        category: "Markets",
        about: "A bustling market featuring a variety of thrift vendors selling clothing, accessories, and home goods.",
        website: "http://www.thriftmarket.com",
        openingHours: {
            monday: { open: "09:00", close: "17:00" },
            tuesday: { open: "09:00", close: "17:00" },
            wednesday: { open: "09:00", close: "17:00" },
            thursday: { open: "09:00", close: "17:00" },
            friday: { open: "09:00", close: "19:00" },
            saturday: { open: "09:00", close: "19:00" },
            sunday: { open: "10:00", close: "16:00" },
        },
    },
    {
        name: "Pop-Up Treasures",
        address: "951 Event Blvd, Fleamarket City",
        phone: "555-1478",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage5.jpg`],
        rating: 4.5,
        category: "Markets",
        about: "A vibrant pop-up event space hosting various thrift sellers and vintage vendors on weekends.",
        website: "http://www.popuptreasures.com",
        openingHours: {
            monday: { open: "Closed", close: "Closed" },
            tuesday: { open: "Closed", close: "Closed" },
            wednesday: { open: "Closed", close: "Closed" },
            thursday: { open: "Closed", close: "Closed" },
            friday: { open: "10:00", close: "18:00" },
            saturday: { open: "10:00", close: "18:00" },
            sunday: { open: "10:00", close: "16:00" },
        },
    },
    // --- Music ---
    {
        name: "Vinyl Vibes",
        address: "357 Music Ave, Soundtown",
        phone: "555-2589",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage1.jpg`],
        rating: 4.9,
        category: "Music",
        about: "A haven for vinyl enthusiasts, offering a wide selection of records across various genres.",
        website: "http://www.vinylvibes.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    {
        name: "Sound Sanctuary",
        address: "753 Groove St, Beatcity",
        phone: "555-3697",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage2.jpg`],
        rating: 4.8,
        category: "Music",
        about: "A unique music store offering vinyl records, CDs, and music memorabilia.",
        website: "http://www.soundsanctuary.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    // --- Comic ---
    {
        name: "Comic Corner",
        address: "159 Hero Ln, Fandom City",
        phone: "555-7412",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage3.jpg`],
        rating: 4.7,
        category: "Comic",
        about: "A paradise for comic book lovers, featuring a vast collection of comics, graphic novels, and collectibles.",
        website: "http://www.comiccorner.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
    {
        name: "Collectible Haven",
        address: "357 Treasure St, Geekville",
        phone: "555-8523",
        cuisine: "N/A",
        images: [`${BASE_URL}/uploads/stores/vintage4.jpg`],
        rating: 4.6,
        category: "Comic",
        about: "Offering a wide range of collectibles, from action figures and toys to rare comics and memorabilia.",
        website: "http://www.collectiblehaven.com",
        openingHours: {
            monday: { open: "10:00", close: "18:00" },
            tuesday: { open: "10:00", close: "18:00" },
            wednesday: { open: "10:00", close: "18:00" },
            thursday: { open: "10:00", close: "18:00" },
            friday: { open: "10:00", close: "20:00" },
            saturday: { open: "10:00", close: "20:00" },
            sunday: { open: "12:00", close: "16:00" },
        },
    },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Store.deleteMany({});
    console.log("🗑️ Old stors deleted");

    await Store.insertMany(data);
    console.log(`✅ Seeded ${data.length} entries`);
  } catch (err) {
    console.error("❌ Seed error:", err);
  } finally {
    await mongoose.disconnect();
  }
})();
