import mongoose from "mongoose";
import "dotenv/config";
import Store from "../models/Store.js";

const BASE_URL = process.env.BASE_URL || "http://localhost:4000";

const data = [
  // --- Vintage ---
  {
    name: "Bahamas Thrift",
    address: "46 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "079 086 1248",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/BahamasThrift/BTimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about: "We sell vintage clothes and street wear",
    website: "http://www.bahamasthrift.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "18:00 pm" },
      tuesday: { open: "10:00 am", close: "18:00 pm" },
      wednesday: { open: "10:00 am", close: "18:00 pm" },
      thursday: { open: "10:00 am", close: "18:00 pm" },
      friday: { open: "10:00 am", close: "18:00 pm" },
      saturday: { open: "10:00 am", close: "18:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "KaapDiem Thrift",
    address: "92 Wale St, Cape Town City Centre, Cape Town, 8001",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/KaapdiemThrift/KTimg6.png`,
    ],
    rating: 4.6,
    category: "Vintage",
    about: "We love pre-loved clothing",
    website: "https://www.instagram.com/kaapdiemthrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Barley Bloset",
    address: "114 Lower Main Rd, Observatory, Cape Town",
    phone: "063 178 9456",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/BarleysBloset/BBimg5.png`,
    ],
    rating: 4.6,
    category: "Vintage",
    about:
      "Consciously Curated Second Hand Shopping Barley's Bloset is a thrift and vintage clothing store in Observatory, Cape Town, which is curated by Carley Adonis. It operates both a physical store and an online shop, and also hosts regular markets.",
    website: "https://barleysbloset.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "17:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "YBMV Collective",
    address: "285B Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "077 444 2331",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/YBMVCollective/YBMVCimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "YBMV Collective, originally named You Butterfly Me Vintage, started in 2016 as a part-time high-school passion project of our founder. In 2020, our team grew & our brand developed into a full-time position, which we re-branded & re-established as a collective space selling a wide selection of fashion products. We offer high-quality, carefully curated fashion items for our fashion-forward & conscious consumers. Now, in 2025 you can shop YBMV Collective all week at our shop in Observatory as well as every weekend at The Neighbourgoods Market at The Old Biscuit Mill, in Woodstock!",
    website: "https://ybmvcollective.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { open: "11:00 am", close: "15:00 pm" },
    },
  },
  {
    name: "Coat King",
    address: "145 M4, Claremont, Cape Town, 7708",
    phone: "021 683 0504",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/CoatKing/CKimg6.png`,
    ],
    rating: 4.4,
    category: "Vintage",
    about:
      "A treasure trove of vintage clothing and accessories from the 60s, 70s, and 80s.",
    website: "https://www.instagram.com/coat_king_wholesalers/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Just Your Luck Vintage Store",
    address: "69 Lower Main Rd, Observatory, Cape Town, 7780",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg5.png`,
      `${BASE_URL}/uploads/stores/Clothing/JustYourLuckVintageStore/JYLVSimg6.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "🍀Welcome to Justyourluck 🍀 Discover a unique shopping experience where quality meets affordability. We offer a curated selection of both second-hand and new clothing, ensuring that everyone can find stylish pieces without breaking the bank. Whether you’re hunting for vintage finds or the latest trends, we've got something for everyone. Come explore our collection at 69 Lower Main Road Observatory.",
    website: "https://www.instagram.com/justyourluck_cpt/?hl=en",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Qeftys",
    address: "66 Albert Road, Cape Town",
    phone: "067 684 8561",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/Qeftys/Qimg5.png`,
    ],
    rating: 5,
    category: "Vintage",
    about:
      "Qeftys is a store that holds high quality clothing for men and women, Local and foreign brands included. Our focus is on making luxury quality affordable. Giving you exclusive items. Our clothing are at times, 1of 1, and at times 2 pieces per item, giving a taste of exclusivity to your fashion taste.",
    website: "https://www.instagram.com/qeftys/",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "15:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Tears Charity",
    address: "281 Main Rd, Retreat, Cape Town, 7950",
    phone: "074 168 8514",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg1.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg2.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg3.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg4.png`,
      `${BASE_URL}/uploads/stores/Clothing/TearsThriftShop/TTSimg5.png`,
    ],
    rating: 4.3,
    category: "Vintage",
    about:
      "TEARS Charity Shops bring in about a third of our income. Without the money that our shops bring in, we would not be able to help nearly as many dogs and cats as we do. Always accepting donations.",
    website: "https://tears.org.za/thrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "13:00 pm" },
    },
  },
  // --- Handmade ---
  {
    name: "Wool World",
    address: "332 Victoria Rd, Salt River, Cape Town, 7925",
    phone: "021 448 4004",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/WoolWorld/WWimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/WoolWorld/WWimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/WoolWorld/WWimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/WoolWorld/WWimg4.png`,
      `${BASE_URL}/uploads/stores/Handmade/WoolWorld/WWimg5.png`,
    ],
    rating: 4.2,
    category: "Handmade",
    about:
      "Knitting Wool Retailers - We stock a wide range of quality knitting yarns, needles and accessories from leading brands such as Patons, King Cole, Sirdar, Stylecraft, Rico, Debbie Bliss, Rowan and many more. We also have a large selection of patterns to choose from.",
    website: "http://www.woolworld.co.za",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "13:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Pritty Bits",
    address: "51 Fitzroy St, Cape Town, 7460",
    phone: "083 441 1311",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/PrettyBits/PBimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/PrettyBits/PBimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/PrettyBits/PBimg3.png`,
    ],
    rating: 5,
    category: "Handmade",
    about:
      "Resin Art Workshops in Cape Town. Join our workshops and experience what resin art is about. Have fun creating your masterpiece by mixing your resin, choosing your colours and pouring your creation! Choose between coasters, cheeseboards, cake stands, river tables and more! We also make personalised resin items on an order basis. This includes wedding favours, wedding ring trays, resin plaques and more!",
    website: "http://www.prettybits.co.za",
    openingHours: {
      monday: { open: "10:00 am", close: "16:00 pm" },
      tuesday: { open: "10:00 am", close: "16:00 pm" },
      wednesday: { open: "10:00 am", close: "16:00 pm" },
      thursday: { open: "10:00 am", close: "16:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "Closed", close: "Closed" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Perfume Prive Workshop",
    address: "2 Huguenot St, Franschhoek, 7690",
    phone: "072 342 4174",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/PerfumePriveWorkshop/PPWimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/PerfumePriveWorkshop/PPWimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/PerfumePriveWorkshop/PPWimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/PerfumePriveWorkshop/PPWimg4.png`,
      `${BASE_URL}/uploads/stores/Handmade/PerfumePriveWorkshop/PPWimg5.png`,
    ],
    rating: 4.9,
    category: "Handmade",
    about:
      "Gold Package Cost- R620 includes a 2-hour Gold Perfume Workshop at Perfume Prive. • The Gold Package is suitable for men and women. Ideal for team-building, women’s day, bachelorette/birthday parties, corporate/year-end functions, fundraisers. Plus, your created Bottle of 10ml Concentrated Perfume Oil and a Perfumed Body Cream Platinum Package Cost - R750 p.p Deal includes a 3-hour Signature Scent Workshop plus your created Bottle of 20ml Concentrated Perfume Oil and a Perfumed Body Cream Diamond Package Cost - R850 Your 10ml Concentrated Perfume Oil, perfume body cream and unique chance to create, bottle and enclose your very own signature 50ml perfume Ultimate Package for two Cost - R2300 for 2 Our Ultimate perfume workshop!",
    website: "https://www.perfumepriveworkshops.com/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Twisted by two",
    address: "Instagram Shop",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg4.png`,
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg5.png`,
      `${BASE_URL}/uploads/stores/Handmade/TwistedByTwo/TBTimg6.png`,
    ],
    rating: 4.8,
    category: "Handmade",
    about: "handcrafted crochet magic",
    website: "https://www.instagram.com/twistedbytwo/?hl=en",
  },
  {
    name: "Denga Candles & Decoration",
    address: "Caledon St, Somerset West, Cape Town, 7129",
    phone: "082 061 4575",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/DengaCandlesAndDecoration/DCADimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/DengaCandlesAndDecoration/DCADimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/DengaCandlesAndDecoration/DCADimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/DengaCandlesAndDecoration/DCADimg4.png`,
    ],
    rating: 4.4,
    category: "Handmade",
    about:
      "Denga Candles and Decoration store, located in Somerset West, near Cape Town, is a popular spot for finding all kind of candles, unique gifts and decorative items since 2013. We are known for our friendly staff and wide selection - from all over the world till handmade in South Africa. Specifically, we carry brands like Kringle® Candles, Bolsius®, Greenleaf® and Denga® Candles.",
    website: "https://www.dengacandle.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "13:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Rockchin",
    address: "35 Main Rd, Hout Bay, Cape Town, 7806",
    phone: "064 661 5746",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg4.png`,
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg5.png`,
      `${BASE_URL}/uploads/stores/Handmade/Rockchin/Rimg6.png`,
    ],
    rating: 4.7,
    category: "Handmade",
    about:
      "Rockchic Gemstones and Crystals in the beautiful village of Hout Bay near Cape Town in South Africa was started in September 2005 , specialising in gemstones, gemstone jewellery and sterling silver jewellery. We source interesting silver jewellery from all over the world and also sell unique beaded pieces, individually designed and hand-made by our own designers.",
    website: "https://www.rockchic.co.za/",
    openingHours: {
      monday: { open: "09:30 am", close: "17:00 pm" },
      tuesday: { open: "09:30 am", close: "17:00 pm" },
      wednesday: { open: "09:30 am", close: "17:00 pm" },
      thursday: { open: "09:30 am", close: "17:00 pm" },
      friday: { open: "09:30 am", close: "17:00 pm" },
      saturday: { open: "09:30 am", close: "17:00 pm" },
      sunday: { open: "09:30 am", close: "16:00 pm" },
    },
  },
  {
    name: "Baraka Gifts and Decor",
    address: "27 Somerset Rd, Green Point, Cape Town, 8005",
    phone: "021 425 8883",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Handmade/BarakaGiftsAndDecor/BGADimg1.png`,
      `${BASE_URL}/uploads/stores/Handmade/BarakaGiftsAndDecor/BGADimg2.png`,
      `${BASE_URL}/uploads/stores/Handmade/BarakaGiftsAndDecor/BGADimg3.png`,
      `${BASE_URL}/uploads/stores/Handmade/BarakaGiftsAndDecor/BGADimg4.png`,
    ],
    rating: 4.8,
    category: "Handmade",
    about:
      "Baraka Gifts and Decor is a world renowned gift shop situated in Cape Town. Recently refurbished, it is now double the size. Allow us to take you on an inspiring journey to a world filled with an eclectic mix of arts, crafts, jewellery, décor and much more. For us, design and social responsibility go hand in hand. Therefore we try to sell as much recycled items as possible, while we do our best to buy directly from small, independent craftsmen and –women from South Africa and the rest of the continent.",
    website: "https://www.barakashop.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { open: "10:00 am", close: "14:00 pm" },
    },
  },
  // --- Bookstores ---
  {
    name: "Obz Books",
    address: "76 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "082 892 8172",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ObzBooks/OBimg6.png`,
    ],
    rating: 4.3,
    category: "Bookstores",
    about:
      "A cozy independent bookstore with a curated selection of books, stationery, and gifts.",
    website: "https://www.obzbooks.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "18:00 pm" },
      sunday: { open: "10:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "Tears Charity",
    address: "281 Main Rd, Retreat, Cape Town, 7950",
    phone: "074 168 8514",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg6.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg7.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TearsCharity/TCimg8.png`,
    ],
    rating: 4.3,
    category: "Bookstores",
    about:
      "TEARS Charity Shops bring in about a third of our income. Without the money that our shops bring in, we would not be able to help nearly as many dogs and cats as we do. Always accepting donations.",
    website: "https://tears.org.za/thrift/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "13:00 pm" },
    },
  },
  {
    name: "The Book Lounge",
    address:
      "Cnr Buitenkant, 71 Roeland St, Cape Town City Centre, Cape Town, 8001",
    phone: "021 462 2425",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/TheBookLounge/TBLimg6.png`,
    ],
    rating: 4.7,
    category: "Bookstores",
    about:
      "An independent bookshop in the heart of Cape Town - we are passionate about what we do!",
    website: "https://booklounge.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "16:00 pm" },
      sunday: { open: "10:00 am", close: "16:00 pm" },
    },
  },
  {
    name: "The Bookworm",
    address: "20 1st Ave, Fish Hoek, Cape Town, 7974",
    phone: "079 309 8435",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Bookworm/Bimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "A delightful shop offering a wide range of books, journals, and high-quality stationery products.",
    website: "http://www.paperandink.com",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "09:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Paper Moon Book Shop",
    address: "105 Roodebloem Rd, Woodstock, Cape Town, 7925",
    phone: "082 444 0444",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/Papermoon/Pimg6.png`,
    ],
    rating: 4.8,
    category: "Bookstores",
    about:
      "Carefully selected second hand books, in almost new condition We also sell: - Art prints - Magazines We also have another store in York Road, Muizenberg.",
    website: "https://www.instagram.com/papermoon.muizenberg/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "17:00 pm" },
      sunday: { open: "10:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Readers Den",
    address: "25 Barnstaple Rd, Wynberg, Cape Town, 7800",
    phone: "021 671 9551",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ReadersDen/RDimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "Family-owned shop since 1992 supplying imported comic books, graphic novels, action figures & manga.",
    website: "https://readersden.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Bikini Beach Books",
    address: "41 Beach Rd, Gordons Bay Central, Cape Town, 7151",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BikiniBeachBook/BBBimg6.png`,
    ],
    rating: 4.4,
    category: "Bookstores",
    about:
      "This laid-back outpost for reading material has piles of secondhand titles on diverse subjects.",
    website: "https://www.instagram.com/bikini-beach-books/?hl=en",
    openingHours: {
      monday: { open: "20:00 am", close: "19:00 pm" },
      tuesday: { open: "20:00 am", close: "19:00 pm" },
      wednesday: { open: "20:00 am", close: "19:00 pm" },
      thursday: { open: "20:00 am", close: "19:00 pm" },
      friday: { open: "20:00 am", close: "19:00 pm" },
      saturday: { open: "20:00 am", close: "19:00 pm" },
      sunday: { open: "20:00 am", close: "19:00 pm" },
    },
  },
  {
    name: "Bargain Books",
    address: "Forest Dr Service Rd, Pinelands, Cape Town, 7405",
    phone: "021 532 2217",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/BargainBooks/BBimg6.png`,
    ],
    rating: 4.7,
    category: "Bookstores",
    about:
      "Bargain Books is South Africa’s most budget-friendly and widest ranged book retailer. Spanning over more than 80 stores across all nine provinces, our primary intention is to provide good books at the best possible prices, in a welcoming environment. We choose our dedicated and passionate booksellers very carefully and try our best to be attentive to every segment of the reading community. We are passionate about bestsellers, new authors; and children's books - recognising the importance of affordable reading in childhood. We want you to have a positive experience in our stores, get value for your money, a wide range to choose from, and enjoy a rewarding and stress-free visit.",
    website: "https://www.instagram.com/bargainbookssa/",
    openingHours: {
      monday: { open: "09:00 am", close: "18:00 pm" },
      tuesday: { open: "09:00 am", close: "18:00 pm" },
      wednesday: { open: "09:00 am", close: "18:00 pm" },
      thursday: { open: "09:00 am", close: "18:00 pm" },
      friday: { open: "09:00 am", close: "18:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "14:00 pm" },
    },
  },
  {
    name: "Clarkes Book Shop",
    address: "199 Long St, Cape Town City Centre, Cape Town, 8001",
    phone: "021 423 5739",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg1.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg2.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg3.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg4.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg5.png`,
      `${BASE_URL}/uploads/stores/BooksStores/ClarkesBookShop/CBSimg6.png`,
    ],
    rating: 4.6,
    category: "Bookstores",
    about:
      "Independent bookshop specialising in African and South African books",
    website: "https://clarkesbooks.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "17:00 pm" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "10:30 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  // --- Markets ---
  {
    name: "Dorp Street Sunday Market",
    address: "53 dorp street, Stellenbosch, Western Cape 7600",
    phone: "074 704 7800",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/DorpaStreetsSundayMarket/DSSMimg6.png`,
    ],
    rating: 4.3,
    category: "Markets",
    about:
      "A fresh, open-air streetside market in Stellenbosch, Dorp Street. The market is filled with hard working entrepreneurs and small businesses. Come and see what the buzz is about and enjoy a relaxing day of strolling through the beautiful Winelands nature scenery.",
    website: "https://www.instagram.com/dorpstreetsundaymarket/?hl=en",
  },
  {
    name: "The Candor Market",
    address: "Sandown Road, Campground Rd, Rondebosch, Cape Town, 7700",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/CandorMarket/CMimg6.png`,
    ],
    rating: 5,
    category: "Markets",
    about:
      "Candor Market is a curated community space empowering the circular economy through conscious entrepreneurship. We bring together small businesses and mindful consumers in a welcoming atmosphere dedicated to positive impact, sustainability, and wholesome vibes!",
    website: "https://www.thecandormarket.com/",
    openingHours: {
      saturday: { open: "Select Saturdays only" },
    },
  },
  {
    name: "Godwood Bargains Market",
    address: "54 Milton Rd, Goodwood Estate, Cape Town, 7460",
    phone: "064 529 8020",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/GoodwoodBargainsMarket/GBMimg3.png`,
    ],
    rating: 4.5,
    category: "Markets",
    about:
      "Turn your closet into cash or enjoy shopping incredible bargains on all things preloved fashion,vintage, fluffy, glitzy, vintage, home decor and so much more ... An amazing vibe with fabulous and friendly vendors. More than just a market...we are a family with a passion for keeping things circular. Find us every first Saturday if the month...don't miss it as each month brings new treasures!",
    website: "https://www.instagram.com/thegoodwoodmarket/?hl=en",
    openingHours: {
      monday: { close: "Closed" },
      tuesday: { close: "Closed" },
      wednesday: { close: "Closed" },
      thursday: { close: "Closed" },
      friday: { close: "Closed" },
      saturday: { open: "09:00 am", close: "14:00 pm" },
      sunday: { close: "Closed" },
    },
  },
  {
    name: "Milnerton Market",
    address: "126 Marine Dr, Paarden Eiland, Cape Town, 7405",
    phone: "021 551 7879",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/MilnertonMarket/MMimg5.png`,
    ],
    rating: 4.1,
    category: "Markets",
    about:
      "Milnerton Market is a vibrant hub for thrift lovers and vintage enthusiasts. Discover unique second-hand treasures, retro fashion, and nostalgic finds in a lively atmosphere. Whether you're hunting for classic clothing or quirky collectibles, Milnerton Market offers a diverse range of pre-loved items that cater to all tastes. Join us for a fun and sustainable shopping experience!",
    website: "https://www.instagram.com/milnertonmarket/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "08:00 am", close: "14:00 pm" },
      sunday: { open: "08:00 am", close: "15:00 pm" },
    },
  },
  {
    name: "Flea Market",
    address: "Western Cape, South Africa, Muizenberg",
    phone: "021 788 7881",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/FleaMarket/FMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/FleaMarket/FMimg2.png`,
    ],
    rating: 4.2,
    category: "Markets",
    about:
      "The Muizenberg Flea Market is a vibrant hub for thrift lovers and vintage enthusiasts. Discover unique second-hand treasures, retro fashion, and nostalgic finds in a lively atmosphere. Whether you're hunting for classic clothing or quirky collectibles, the Muizenberg Flea Market offers a diverse range of pre-loved items that cater to all tastes. Join us for a fun and sustainable shopping experience!",
    website: "https://www.instagram.com/muizenberg-flea-market/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "Closed", close: "Closed" },
      sunday: { open: "08:30 am", close: "17:00 pm" },
    },
  },
  {
    name: "Oranjezicht Farm Market",
    address:
      "Haul Road, Granger Bay Blvd, Victoria & Alfred Waterfront, Cape Town, 8001",
    phone: "083 628 3426",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/OranjezichtFarmMarket/OFMimg5.png`,
    ],
    rating: 4.7,
    category: "Markets",
    about:
      "A good market is about more than buying groceries - it’s about striking up conversations, feeling part of a community, buying locally and eating with the seasons. Engage with the more than 65 producers of fresh produce, cheese, free-range meat, eggs and sustainably harvested fish. There is also plenty to eat on site for meat-lovers, vegans and vegetarians - its healthy and delicious. Located in a quiet part of the V&AW, there is seating, good music and sea views. Cash, credit card and Snapscan available. ATM on site. There is no fee to enter the market. Pedestrian entrances are open directly from The Granger Bay Parking Garage as well as on Beach Road, and cyclists, joggers and dog walkers are most welcome.",
    website: "https://www.instagram.com/ozcfarm/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "04:00 am", close: "21:00 pm" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "08:00 am", close: "14:00 pm" },
      sunday: { open: "08:30 am", close: "14:00 pm" },
    },
  },
  {
    name: "Trench Town Pop Ups",
    address: "143 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "083 298 8388",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg1.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg2.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg3.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg4.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg5.png`,
      `${BASE_URL}/uploads/stores/Market/TrenchTownPopUp/TTPUimg6.png`,
    ],
    rating: 4.6,
    category: "Markets",
    about:
      "We are Trench Town Pop Ups. A collaborative 3 day a week permanent pop up stall on the lovely grounds of Trench Town Obs. Thursday evenings are a vibey night market whilst Saturday mornings is the big family market. Come check out the best vendors, food, vibe and restaurant.",
    website: "https://www.instagram.com/trenchtown_obs/?hl=en",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "04:00 am", close: "20:00 pm" },
      friday: { open: "12:00 am", close: "20:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Neighbourgoods Market",
    address: "373 Albert Rd, Woodstock, Cape Town, 7925",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg1.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg2.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg3.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg4.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg5.png`,
      `${BASE_URL}/uploads/stores/Market/NeighbourGoodsMarket/NGMimg6.png`,
    ],
    rating: 4.5,
    category: "Markets",
    about:
      "The Neighbourgoods Market is a weekly market place and cultural event held at The Old Biscuit Mill in Woodstock, Cape Town. Held every weekend of the year, this is the essential meeting ground for the city's cosmopolitan community to gather and enjoy the bounty of food, design, fashion and music that define the Mother City. Now in it’s 18th year, this award-winning market features over 100 specialty traders every Saturday, creating a weekly showcase for Cape Town’s most exciting street food chefs, artisanal producers, local designers, musicians and merchants to gather and display their work in a festive celebration of local creative culture.",
    website: "https://www.instagram.com/neighbourgoodsmarket/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "Closed", close: "Closed" },
      thursday: { open: "Closed", close: "Closed" },
      friday: { open: "Closed", close: "Closed" },
      saturday: { open: "09:00 am", close: "15:00 pm" },
      sunday: { open: "10:00 am", close: "15:00 pm" },
    },
  },
  // --- Music ---
  {
    name: "Slow Life Records",
    address: "84 Main Rd, Kalk Bay, Cape Town, 7975",
    phone: "082 892 0350",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg5.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/SlowLifeRecords/SLRimg6.png`,
    ],
    rating: 5,
    category: "Music",
    about:
      "Music, music, music This place is hotter than the Arabian desert on a summers day!! A record, vinyl, lp, CD, casette tape shop for starters and then a platform from where to share details of your event, talk about music",
    website: "https://www.instagram.com/slowliferecords/?hl=en ",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "17:00 pm" },
      sunday: { open: "09:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Voom Voom Records",
    address: "15 Lower Main Rd, Observatory, Cape Town, 7925",
    phone: "082 580 4367",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/VoomVoomMusic/VVMimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/VoomVoomMusic/VVMimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/VoomVoomMusic/VVMimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/VoomVoomMusic/VVMimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/VoomVoomMusic/VVMimg5.png`,
    ],
    rating: 4.5,
    category: "Music",
    about:
      "We are open everyday! Listen to some good music, enjoy the good vibes! We are Voom Voom! The record shop has hosted some famous record diggers from Bonobo, Scratch Bastid, Coldcut, Antal, Henry Rollins and I sold records to Brad Pitt, Danny Krivit, Gilles Peterson, Mr Bongo, Guts and soon..to YOU! We also have a large selection of vintage clothes from fake furs, cargo pants, leather jackets, Hawaiian shirts...plus a selection of exclusive brand like Gucci, Hugo Boss, Valentino, Yves St Laurent, Pierre Cardin, Prada",
    website: "https://www.voomvoomrecords.com/",
    openingHours: {
      monday: { open: "10:00 am", close: "18:00 pm" },
      tuesday: { open: "10:00 am", close: "18:00 pm" },
      wednesday: { open: "10:00 am", close: "18:00 pm" },
      thursday: { open: "10:00 am", close: "18:00 pm" },
      friday: { open: "10:00 am", close: "18:00 pm" },
      saturday: { open: "09:30 am", close: "18:00 pm" },
      sunday: { open: "11:00 am", close: "17:00 pm" },
    },
  },
  {
    name: "Mabu Vinyl",
    address: "285 Long St, Gardens, Cape Town, 8001",
    phone: "079 922 8585",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/MabuVinyl/MVimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MabuVinyl/MVimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MabuVinyl/MVimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MabuVinyl/MVimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MabuVinyl/MVimg5.png`,
    ],
    rating: 4.8,
    category: "Music",
    about:
      "Cape Town record store since 2000. Mostly vintage, with a few local reissues. Also featured in the Searching For Sugarman Documentary. Check our online spaces for Digital Digs, and join the whatsapp list for notifications of fresh arrivals",
    website: "https://mabuvinyl.wordpress.com/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "Closed", close: "Closed" },
      wednesday: { open: "10:00 am", close: "16:00 pm" },
      thursday: { open: "10:00 am", close: "16:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "10:00 am", close: "16:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Turntable Guy",
    address: "71 Durban Rd, Mowbray, Cape Town, 7700",
    phone: "082 927 3552",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/TurntableGuy/TGimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TurntableGuy/TGimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TurntableGuy/TGimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TurntableGuy/TGimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TurntableGuy/TGimg5.png`,
    ],
    rating: 4.8,
    category: "Music",
    about:
      "Turntable Guy specialized in quality turntable sales and turntable repairs. We also stock accessories to get the most from your turntable.",
    website:
      "https://www.turntableguy.co.za/?srsltid=AfmBOooOmgb8PgEOMtJxqaBtKC4Ws9nCAuw5PH7ZAqza5U9J3dLgtln-",
    openingHours: {
      monday: { open: "09:00 am", close: "15:00 pm" },
      tuesday: { open: "09:00 am", close: "15:00 pm" },
      wednesday: { open: "09:00 am", close: "15:00 pm" },
      thursday: { open: "09:00 am", close: "15:00 pm" },
      friday: { open: "09:00 am", close: "15:00 pm" },
      saturday: { open: "09:00 am", close: "12:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Kandi Records",
    address: "7700, 77 Durban Rd, Mowbray, Cape Town, 7700",
    phone: "082 927 3552",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg5.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/KandiRecords/KRimg6.png`,
    ],
    rating: 4.7,
    category: "Music",
    about:
      "Kandi Records buys and sells new and used vinyl records. We also stock CD's and music DVD's and Music related things like badges and record cleaning gear. Kandi Records was opened by Mark in 2014. In 2021 Mark passed away and Kandi was bought over by Jacques from Turntable Guy. We aim to always keep out stock holding fresh and well priced",
    website: "https://www.kandirecords.co/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "17:00 pm" },
      saturday: { open: "10:00 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "The Listening Room",
    address:
      "De Waterkant, Cape Town, 8001, South Africa, Cape Town, South Africa",
    phone: "021 418 4379",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/TheListeningRoom/TLRimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TheListeningRoom/TLRimg2.png`,
    ],
    rating: 4.6,
    category: "Music",
    about:
      "The Listening Room Cape Town is a boutique vinyl and hi-fi equipment store that cares about music and how we listen to it.",
    website: "https://www.thelisteningroom.co.za/",
    openingHours: {
      monday: { open: "09:00 am", close: "16:00 pm" },
      tuesday: { open: "09:00 am", close: "16:00 pm" },
      wednesday: { open: "09:00 am", close: "16:00 pm" },
      thursday: { open: "09:00 am", close: "16:00 pm" },
      friday: { open: "09:00 am", close: "16:00 pm" },
      saturday: { open: "09:00 am", close: "13:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "For The Record",
    address: "46A Canterbury St, District Six, Cape Town, 7925",
    phone: "063 635 9494",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg5.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/ForTheRecord/FTRimg6.png`,
    ],
    rating: 4.9,
    category: "Music",
    about:
      "We are an independent record store based in the centre of Cape Town's East City District. Started by a father and daughter who share a passion for music and collecting vinyls",
    website: "https://www.instagram.com/fortherecord_cpt/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "10:00 am", close: "16:00 am" },
      wednesday: { open: "10:00 am", close: "16:00 am" },
      thursday: { open: "10:00 am", close: "16:00 am" },
      friday: { open: "10:00 am", close: "16:00 am" },
      saturday: { open: "10:00 am", close: "14:00 am" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "M.PIRE Music",
    address: "299 Albert Rd, Woodstock, Cape Town, 7925",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg5.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/MPIREMusic/MMimg6.png`,
    ],
    rating: 4.7,
    category: "Music",
    about:
      "Music and Merchandise-Phonographic Integrated Retail Experience. In a digital world, we wanted to keep some things a little analogue Introducing Cape Town's premier music retail experience. Vinyl's, CD's and merchandise all available at M-PIRE Music",
    website: "https://www.mpiremusic.co.za/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "09:00 am", close: "17:00 pm" },
      wednesday: { open: "09:00 am", close: "17:00 pm" },
      thursday: { open: "09:00 am", close: "17:00 pm" },
      friday: { open: "09:00 am", close: "17:00 pm" },
      saturday: { open: "09:00 am", close: "15:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "The Gear Junkie",
    address: "Cnr Hopkins & Shannon, 3 Hopkins St, Salt River, Cape Town, 7925",
    phone: "021 447 0269",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/TheGearJunkie/TGJimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TheGearJunkie/TGJimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/TheGearJunkie/TGJimg3.png`,
    ],
    rating: 4.8,
    category: "Music",
    about:
      "Traders in vintage and pre-loved musical equipment. We also offer structural repairs, setups, restrings etc to instruments as well as electronic repairs to amplifiers, speakers etc",
    website: "https://www.thegearjunkie.co.za/",
    openingHours: {
      monday: { open: "10:00 am", close: "17:00 pm" },
      tuesday: { open: "10:00 am", close: "17:00 pm" },
      wednesday: { open: "10:00 am", close: "17:00 pm" },
      thursday: { open: "10:00 am", close: "17:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "10:00 am", close: "13:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
  {
    name: "Roastin’ Records",
    address: "28 Wandel St, Gardens, Cape Town, 8001",
    phone: "",
    cuisine: "N/A",
    images: [
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg1.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg2.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg3.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg4.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg5.png`,
      `${BASE_URL}/uploads/stores/VinylsStores/RoastinRecords/RRimg6.png`,
    ],
    rating: 4.9,
    category: "Music",
    about:
      "VINYL Records - specialising in Local South African Music and Imports - CDs - T-Shirts - Cassettes - COFFEE & Much More :) Plattenladen !!!",
    website: "https://roastinrecords.com/",
    openingHours: {
      monday: { open: "Closed", close: "Closed" },
      tuesday: { open: "10:00 am", close: "16:00 pm" },
      wednesday: { open: "10:00 am", close: "16:00 pm" },
      thursday: { open: "10:00 am", close: "16:00 pm" },
      friday: { open: "10:00 am", close: "16:00 pm" },
      saturday: { open: "10:00 am", close: "14:00 pm" },
      sunday: { open: "Closed", close: "Closed" },
    },
  },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Store.deleteMany({});
    console.log("🗑️ Old stors deleted");

    await Store.insertMany(data);
    console.log(`✅ Seeded ${data.length} entries`);
  } catch (err) {
    console.error("❌ Seed error:", err);
  } finally {
    await mongoose.disconnect();
  }
})();
